#Germany
province = {
	id = 483 #Oslo
	supplypool  = 20
	oilpool = 20
 } 
#Australia
province = {
	id = 1607 #Port Moresby
	supplypool  = 2
} 
province = {
	id = 1710 #Hobart
	supplypool = 5
}
#Belgium
province = {
	id = 894 #Matadi
	supplypool = 5
}
#France
province = {
	id = 728 #Oran
	supplypool = 50
}
province = {
	id = 1002 #Tamatave
	supplypool = 5
}
#Greece
province = {
	id = 382 #Irakleio
	supplypool = 5
}
#Italy
province = {
	id = 435 #Sassari
	supplypool = 10
	oilpool = 2
}
province = {
	id = 359 #Tirana
	supplypool = 10
	oilpool     = 5
} 
province = {
	id = 765 #Tobruk
	supplypool = 15
	oilpool = 5
}
province = {
	id = 378 #Kalymnos
	supplypool = 5
	oilpool = 2
}
province = {
	id = 379 #Rhodes
	supplypool = 5 
	oilpool = 2 
}
#Japan
province = {
	id = 1219 #Port Arthur
	supplypool = 5
	oilpool = 2
}
province = {
	id = 1232 #Busan
	supplypool = 5
	oilpool = 2
}
province = {
	id = 1245 #Tangshan
	supplypool = 100
	oilpool = 20
}
province = {
	id = 1358 #Fuzhou
	supplypool = 5
}
province = {
	id = 1362 #Taipei
	supplypool = 10
	oilpool = 5
}
province = {
	id = 1365 #Haikou
	supplypool  = 2
	oilpool     = 2
}
province = {
	id = 1367 #Naoming
	supplypool  = 5
}
province = {
	id = 1369 #Guangzhou
	supplypool = 5
	oilpool = 2
}
province = {
	id = 1542 #TOYOHARA
	supplypool = 5
}
province = {
	id = 1563 #Southern Okinawa
	supplypool = 5
}
province = {
	id = 1661 #Iwo Jima
	supplypool = 5
}
province = {
	id = 1665 #Ponape
	supplypool = 5
}
province = {
	id = 1666 #Kusaie
	supplypool = 5
}
province = {
	id = 1667 #Truk
	supplypool = 7
	oilpool = 7
}
province = {
	id = 1668 #Woleai
	supplypool = 5
}
province = {
	id = 1669 #Yap
	supplypool = 5
}
province = {
	id = 1670 #Peleliu
	supplypool = 5
}
province = {
	id = 1672 #Minami Torishima
	supplypool = 5
}
province = {
	id = 1674 #Bikini
	supplypool = 5
}
province = {
	id = 1675 #Eniwetok
	supplypool = 5
}
province = {
	id = 1676 #Kwajalein
	supplypool = 10
	oilpool = 5
}
province = {
	id = 1677 #Majuro
	supplypool = 5
}
province = {
	id = 1681 #Wotje
	supplypool = 5
}
province = {
	id = 1685 #Saipan
	supplypool = 5
}
province = {
	id = 1686 #Pagan
	supplypool = 5
}
#New Zealand
province = {
	id = 1723 #Dunedin
	supplypool = 10
	oilpool = 5
}
#Portugal
province = {
	id = 963 #Bissau
	supplypool = 5
}
#Spain
province = {
	id = 475 #Palma de Mallorca
	supplypool = 10
	oilpool = 5
}
province = {
	id = 715 #Tangiers
	supplypool = 10
}
province = {
	id = 990 #Canaria
	supplypool = 10
	oilpool = 5
}
#Sweden
province = {
	id = 2156 #Visby
	supplypool = 5
}
#United Kindgom
province = {
	id = 1 #Reykjavik
   supplypool  = 200
}
province = {
	id = 36 #Belfast
	supplypool  = 5
 } 
province = {
	id = 348 #Gibraltar
	supplypool = 5
}
province = {
	id = 429 #Malta
	supplypool = 10
}
province = {
	id = 789 #Alexandria
	supplypool = 15
	oilpool = 10
}
province = {
	id = 839 #Garissa
	supplypool = 10
}
province = {
	id = 929 #Lagos
	supplypool = 5
}
province = {
	id = 956 #Accra
	supplypool = 5
}
province = {
	id = 1008 #Tel Aviv
	supplypool = 5
}
province = {
	id = 1371 #Hong Kong
	supplypool = 10
	oilpool = 5
}
province = {
	id = 1432 #Singapore
	supplypool = 10
	oilpool = 5
}
province = {
	id = 1511 #Colombo
	supplypool = 10
	oilpool = 5
}
#USA
province = {
	id = 889 #Balboa
	supplypool = 10
	oilpool = 5
}
province = {
	id = 1734 #Pearl Harbour
	supplypool = 15
	oilpool = 15
}
province = {
	id = 1736 #Hawaii
	supplypool = 10
}

