province = { id = 181 points = 5 } #Danzig
province = { id = 226 points = 1 }
province = { id = 224 points = 5 } #Poznan
province = { id = 225 points = 1 }
province = { id = 235 points = 5 } #Krakow
province = { id = 227 points = 1 }
province = { id = 221 points = 1 }
province = { id = 223 points = 5 } #Lodz
province = { id = 231 points = 1 }
province = { id = 233 points = 1 }
province = { id = 232 points = 10 } #Warszawa
province = { id = 222 points = 1 }
province = { id = 230 points = 1 }
province = { id = 242 points = 5 } #Lwow
province = { id = 229 points = 1 }
province = { id = 228 points = 1 }
province = { id = 234 points = 1 }
province = { id = 237 points = 1 }
province = { id = 236 points = 1 }
province = { id = 247 points = 5 } #Brest-Litovsk
province = { id = 239 points = 1 }
province = { id = 246 points = 1 }
province = { id = 250 points = 1 }
province = { id = 254 points = 1 }
province = { id = 255 points = 1 }
province = { id = 258 points = 5 } #Vilna
province = { id = 253 points = 1 }
province = { id = 245 points = 1 }
province = { id = 241 points = 1 }
province = { id = 240 points = 1 }
province = { id = 238 points = 1 }
province = { id = 244 points = 1 }
province = { id = 249 points = 1 }
province = { id = 248 points = 1 }
province = { id = 257 points = 1 }
province = { id = 256 points = 1 }
province = { id = 251 points = 1 }
province = { id = 243 points = 1 }
province = { id = 252 points = 1 }
