province = {
  id = 1 # 레이캬비크 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 5 # 스캐퍼 플로 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 13 # 선더랜드 
  ic = 3
}

province = {
  id = 17 # 맨체스터 
  ic = 5
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 18 # 셰필드 
  ic = 6
}

province = {
  id = 22 # 카디프 
  ic = 4
}

province = {
  id = 23 # 플리머스 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 24 # 버밍엄 
  ic = 4
}

province = {
  id = 25 # 노리치 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 26 # 도버 
  coastalfort = 3
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 27 # 포츠머스 
  coastalfort = 2
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 29 # 런던 
  ic = 3
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 34 # 더블린 
  coastalfort = 2
}

province = {
  id = 36 # 벨파스트 
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 37 # 브레스트 
  coastalfort = 2
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 43 # 셰르부르 
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 50 # 아미앵 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 51 # 됭케르크 
  coastalfort = 4
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 52 # 릴 
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 55 # 파리 
  landfort = 4
  air_base = { size = 4 current_size = 4 }
}

province = {
  id = 64 # 르 크뢰조 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 65 # 부르주 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 68 # 보르도 
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 83 # 포 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 85 # 리옹 
  landfort = 3
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 86 # 툴롱 
  coastalfort = 2
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 87 # 니스 
  landfort = 5
}

province = {
  id = 90 # 그르노블 
  landfort = 3
}

province = {
  id = 95 # 쇼몽 
  landfort = 4
}

province = {
  id = 97 # 벨포르 
  ic = -1
  landfort = 8
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 98 # 퐁탈리에 
  landfort = 3
}

province = {
  id = 99 # 랭스 
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 100 # 베르됭 
  landfort = 8
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 104 # 메스 
  landfort = 10
}

province = {
  id = 105 # 콜마르 
  landfort = 6
}

province = {
  id = 106 # 낭시 
  landfort = 8
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 107 # 스트라스부르 
  landfort = 6
}

province = {
  id = 108 # 리에주 
  ic = -2
  landfort = 1
}

province = {
  id = 112 # 몽스 
  ic = -2
}

province = {
  id = 113 # 나뮈르 
  ic = -2
  landfort = 1
}

province = {
  id = 114 # 브뤼헤 
  ic = -2
  coastalfort = 1
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 115 # 안트베르펜 
  ic = -2
  landfort = 2
}

province = {
  id = 116 # 브뤼셀 
  ic = -2
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 119 # 아른험 
  ic = -2
}

province = {
  id = 122 # 암스테르담 
  ic = -2
  landfort = 3
  coastalfort = 3
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 125 # 로테르담 
  ic = -2
  landfort = 1
  coastalfort = 2
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 129 # 코블렌츠 
  landfort = 3
}

province = {
  id = 130 # 마인츠 
  landfort = 2
}

province = {
  id = 131 # 쾰른 
  landfort = 6
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 132 # 프라이부르크 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 135 # 튀빙겐 
  landfort = 3
}

province = {
  id = 136 # 카를스루에 
  landfort = 3
}

province = {
  id = 139 # 다름슈타트 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 141 # 뮌스터 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 142 # 뒤셀도르프 
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 145 # 에센 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 146 # 하노버 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 147 # 빌헬름스하펜 
  coastalfort = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 148 # 브레멘 
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 152 # 킬 
  coastalfort = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 153 # 로스토크 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 157 # 포츠담 
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 164 # 오펠른 
  landfort = 3
}

province = {
  id = 167 # 브레슬라우 
  landfort = 5
}

province = {
  id = 169 # 마그데부르크 
  landfort = 2
}

province = {
  id = 172 # 콧부스 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 173 # 드레스덴 
  landfort = 3
}

province = {
  id = 175 # 레겐스부르크 
  landfort = 3
}

province = {
  id = 181 # 단치히 
  landfort = 2
}

province = {
  id = 184 # 쾨니히스베르크 
  landfort = 4
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 185 # 알렌슈타인 
  landfort = 4
}

province = {
  id = 187 # 린츠 
  ic = -1
  landfort = 1
}

province = {
  id = 188 # 아이젠슈타트 
  ic = -1
}

province = {
  id = 190 # 그라츠 
  ic = -1
}

province = {
  id = 195 # 빈 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 196 # 브르노 
  ic = -1
}

province = {
  id = 198 # 흐라데츠 크랄로베 
  ic = -1
}

province = {
  id = 200 # 리베레츠 
  ic = -1
  landfort = 2
}

province = {
  id = 201 # 오스트라바 
  ic = -1
  landfort = 1
}

province = {
  id = 205 # 카를로비 바리 
  ic = -2
}

province = {
  id = 206 # 오파바 
  ic = 1
}

province = {
  id = 207 # 프라하 
  ic = -1
}

province = {
  id = 210 # 코마르노 
  ic = -1
  landfort = 2
}

province = {
  id = 211 # 반스카 비스트리차 
  ic = 2
}

province = {
  id = 212 # 질리나 
  ic = 2
}

province = {
  id = 218 # 프레데릭스하운 
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 221 # 카토비체 
  ic = -1
}

province = {
  id = 222 # 토룬 
  landfort = 2
}

province = {
  id = 224 # 포즈난 
  landfort = 1
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 225 # 비드고슈치 
  landfort = 2
}

province = {
  id = 226 # 그디니아 
  landfort = 2
}

province = {
  id = 227 # 쳉스토호바 
  ic = -2
}

province = {
  id = 228 # 시에들체 
  landfort = 2
}

province = {
  id = 229 # 오스트로웽카 
  landfort = 3
}

province = {
  id = 232 # 바르샤바 
  ic = -2
  landfort = 5
}

province = {
  id = 234 # 라돔 
  ic = -1
}

province = {
  id = 235 # 크라쿠프 
  ic = -2
  landfort = 3
}

province = {
  id = 239 # 프셰미실 
  landfort = 4
}

province = {
  id = 242 # 리비우 
  landfort = 2
}

province = {
  id = 243 # 루블린 
  ic = -1
  landfort = 1
}

province = {
  id = 244 # 루브네 
  landfort = 2
}

province = {
  id = 245 # 루츠크 
  landfort = 1
}

province = {
  id = 247 # 브레스트-리토프스크 
  landfort = 4
}

province = {
  id = 250 # 우옴자 
  landfort = 3
}

province = {
  id = 255 # 그로드노 
  landfort = 2
}

province = {
  id = 262 # 카우나스 
  ic = -2
  landfort = 4
}

province = {
  id = 264 # 리가 
  ic = -1
  landfort = 2
  coastalfort = 3
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 266 # 다우가프필스 
  ic = -1
  landfort = 5
}

province = {
  id = 268 # 리에파야 
  ic = -1
  landfort = 1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 270 # 탈린 
  ic = -4
  landfort = 2
  coastalfort = 2
}

province = {
  id = 275 # 쿠레사아레 
  coastalfort = 1
}

province = {
  id = 277 # 페치 
  ic = -1
}

province = {
  id = 279 # 죄르 
  ic = -2
}

province = {
  id = 280 # 세게드 
  ic = -2
}

province = {
  id = 281 # 데브레첸 
  ic = -3
}

province = {
  id = 282 # 미슈콜츠 
  ic = -4
}

province = {
  id = 283 # 베케슈처버 
  ic = -1
}

province = {
  id = 284 # 부다페스트 
  ic = -6
  landfort = 2
}

province = {
  id = 285 # 티미쇼아라 
  landfort = 2
}

province = {
  id = 286 # 아라드 
  ic = -2
  landfort = 2
}

province = {
  id = 291 # 시비우 
  ic = -3
  landfort = 2
}

province = {
  id = 294 # 코펜하겐 
  landfort = 2
  coastalfort = 3
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 295 # 레시차 
  landfort = 2
}

province = {
  id = 307 # 도브리치 
  ic = 1
}

province = {
  id = 308 # 지우르지우 
  ic = 2
  landfort = 3
}

province = {
  id = 310 # 콘스탄차 
  ic = 3
  coastalfort = 1
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 316 # 부쿠레슈티 
  landfort = 1
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 321 # 소피아 
  ic = -2
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 325 # 부르가스 
  ic = -1
}

province = {
  id = 326 # 바르나 
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 327 # 크루셰바츠 
  ic = 1
}

province = {
  id = 330 # 니시 
  ic = 1
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 331 # 피로트 
  ic = 2
}

province = {
  id = 332 # 체티네 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 333 # 스코페 
  ic = 1
}

province = {
  id = 336 # 페트로브그라드 
  landfort = 2
}

province = {
  id = 338 # 베오그라드 
  ic = 5
  landfort = 2
}

province = {
  id = 339 # 보르 
  ic = 2
  landfort = 1
}

province = {
  id = 344 # 오시예크 
  ic = -1
}

province = {
  id = 345 # 볘로바르 
  ic = 1
}

province = {
  id = 348 # 지브롤터 
  landfort = 6
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 350 # 스플리트 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 355 # 사라예보 
  landfort = 3
}

province = {
  id = 356 # 모스타르 
  landfort = 3
}

province = {
  id = 359 # 티라나 
  coastalfort = 2
}

province = {
  id = 360 # 코르차 
  province_revoltrisk = 30
}

province = {
  id = 362 # 블로러 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 363 # 크산티 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 364 # 카발라 
  ic = 1
  landfort = 3
}

province = {
  id = 365 # 테살로니키 
  ic = 2
  landfort = 1
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 366 # 코자니 
  ic = 1
}

province = {
  id = 367 # 이오안니나 
  landfort = 1
}

province = {
  id = 377 # 아테네 
  coastalfort = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 378 # 칼림노스 
  coastalfort = 4
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 382 # 이라클리오 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 384 # 갈리폴리 
  coastalfort = 3
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 385 # 아드리아노폴리스 
  infra = 0.4
  landfort = 3
}

province = {
  id = 386 # 카르스 
  landfort = 3
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 390 # 루가노 
  landfort = 2
}

province = {
  id = 391 # 제네바 
  landfort = 2
}

province = {
  id = 392 # 베른 
  landfort = 2
}

province = {
  id = 393 # 브레시아 
  landfort = 3
}

province = {
  id = 395 # 베르가모 
  landfort = 2
}

province = {
  id = 396 # 제노바 
  landfort = 5
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 398 # 토리노 
  landfort = 4
}

province = {
  id = 399 # 알레산드리아 
  landfort = 5
}

province = {
  id = 400 # 베네치아 
  coastalfort = 2
  air_base = { size = 2 current_size = 2 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 401 # 트렌토 
  landfort = 3
}

province = {
  id = 404 # 트리에스테 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 406 # 폴라 
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 409 # 이스탄불 
  infra = 0.1
  landfort = 2
  coastalfort = 1
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 411 # 볼로냐 
  ic = -2
}

province = {
  id = 412 # 안코나 
  coastalfort = 1
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 421 # 나폴리 
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 422 # 타란토 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 426 # 바리 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 429 # 몰타 
  coastalfort = 1
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 430 # 팔레르모 
  coastalfort = 1
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 433 # 시라쿠사 
  coastalfort = 2
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 434 # 칼리아리 
  coastalfort = 1
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 435 # 사사리 
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 436 # 타라고나 
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 441 # 라 코루냐 
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 460 # 마드리드 
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 464 # 발렌시아 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 473 # 카디스 
  naval_base = { size = 5 current_size = 7 }
}

province = {
  id = 475 # 팔마 데 마요르카 
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 476 # 리스본 
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 483 # 오슬로 
  coastalfort = 3
}

province = {
  id = 491 # 올레순 
  coastalfort = 3
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 493 # 트론헤임 
  coastalfort = 2
}

province = {
  id = 495 # 나르비크 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 502 # 아크몰린스크 
  ic = -1
}

province = {
  id = 503 # 카라간다 
  ic = -1
}

province = {
  id = 504 # 알마티 
  ic = -1
}

province = {
  id = 517 # 페차모 
  ic = -1
}

province = {
  id = 520 # 오울루 
  ic = -1
}

province = {
  id = 524 # 투르쿠 
  ic = -1
  coastalfort = 1
}

province = {
  id = 525 # 헬싱키 
  ic = -1
  landfort = 2
  coastalfort = 3
}

province = {
  id = 526 # 아베난마 
  landfort = 2
  coastalfort = 2
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 527 # 탐페레 
  ic = -1
  landfort = 1
}

province = {
  id = 528 # 미켈리 
  ic = -1
  landfort = 1
}

province = {
  id = 529 # 코우볼라 
  ic = -1
}

province = {
  id = 531 # 비푸리 
  landfort = 3
  coastalfort = 1
}

province = {
  id = 533 # 요엔수 
  landfort = 5
}

province = {
  id = 535 # 무르만스크 
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 536 # 칸달락샤 
  ic = -1
}

province = {
  id = 542 # 아르한겔스크 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 553 # 페트로그라드 
  landfort = 5
  coastalfort = 5
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 10 current_size = 10 }
  name = PROV_PETROGRAD
}

province = {
  id = 570 # 자고르스크 
  landfort = 2
}

province = {
  id = 572 # 모스크바 
  ic = -5
  landfort = 3
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 594 # 바브루이스크 
  landfort = 1
}

province = {
  id = 604 # 쿠르스크 
  landfort = 2
}

province = {
  id = 617 # 키예프 
  landfort = 2
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 621 # 티라스폴 
  landfort = 2
}

province = {
  id = 622 # 미콜라이우 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 624 # 헤르손 
  ic = -1
}

province = {
  id = 626 # 오데사 
  ic = -1
  coastalfort = 3
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 633 # 쿠퍈시크 
  ic = -1
}

province = {
  id = 634 # 보로실로브그라드 
  ic = -1
}

province = {
  id = 635 # 바흐무트 
  ic = -3
}

province = {
  id = 641 # 세바스토폴 
  ic = -1
  landfort = 3
  coastalfort = 5
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 644 # 로스토프-나-도누 
  ic = -2
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 663 # 차리친 
  ic = -3
  landfort = 3
  name = PROV_TSARITSYN
}

province = {
  id = 666 # 포크롭스크 
  name = PROV_POKROVSK
}

province = {
  id = 668 # 쿠이비셰프 
  ic = -2
}

province = {
  id = 669 # 사라토프 
  ic = -2
}

province = {
  id = 672 # 카잔 
  ic = -2
}

province = {
  id = 680 # 고르키 
  ic = -1
}

province = {
  id = 684 # 키로프 
  ic = -1
}

province = {
  id = 687 # 페름 
  ic = -5
}

province = {
  id = 688 # 우흐타 
  ic = -1
}

province = {
  id = 690 # 스테를리타마크 
  ic = -1
}

province = {
  id = 706 # 아스트라한 
  ic = -2
}

province = {
  id = 708 # 쿠타이시 
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 709 # 트빌리시 
  ic = -1
}

province = {
  id = 711 # 예레반 
  ic = -1
}

province = {
  id = 713 # 바쿠 
  ic = -1
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 715 # 탕헤르 
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 716 # 나도르 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 717 # 라바트 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 727 # 알제 
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 747 # 튀니스 
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 750 # 트리폴리 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 761 # 벵가지 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 765 # 투브루크 
  landfort = 3
  coastalfort = 2
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 789 # 알렉산드리아 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 791 # 포트 사이드 
  landfort = 2
}

province = {
  id = 815 # 마사와 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 816 # 아사브 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 827 # 고데 
  landfort = 1
}

province = {
  id = 828 # 하라르 
  landfort = 1
}

province = {
  id = 833 # 지부티 
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 835 # 갈카쿄 
  landfort = 2
}

province = {
  id = 836 # 모가디슈 
  landfort = 1
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 838 # 키스마요 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 850 # 다르 에스 살람 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 856 # 마시셰 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 872 # 더반 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 880 # 케이프 타운 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 882 # 스와코프문트 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 889 # 발보아 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 892 # 로비토 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 893 # 카빈다 
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 894 # 마타디 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 909 # 야운데 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 912 # 상 투메 
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 915 # 리브르빌 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 929 # 라고스 
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 963 # 비사우 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 964 # 프리타운 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 969 # 몬로비아 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 978 # 다카르 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 988 # 빌라 시스네로스 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 990 # 라스팔마스 데 그랑 카나리아 
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 992 # 카보 베르데 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 995 # 아조레스 제도 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1002 # 타마타베 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1004 # 엘 아리시 
  infra = -0.3
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1006 # 알 칸타라 
  infra = -0.4
}

province = {
  id = 1007 # 부르 타우피크 
  infra = -0.1
}

province = {
  id = 1008 # 텔 아비브 
  ic = -1
  infra = -0.2
  air_base = { size = 3 current_size = 3 }
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1009 # 가자 
  landfort = 4
}

province = {
  id = 1010 # 에일라트 
  infra = -0.2
  landfort = 4
}

province = {
  id = 1011 # 하이파 
  infra = 0.2
}

province = {
  id = 1013 # 아코 
  infra = 0.2
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 1014 # 데이르 에즈 조르 
  infra = 0.2
}

province = {
  id = 1016 # 다마스쿠스 
  infra = 0.1
}

province = {
  id = 1017 # 힘스 
  infra = 0.4
}

province = {
  id = 1019 # 베이루트 
  infra = -0.1
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1021 # 알레포 
  infra = 0.2
}

province = {
  id = 1022 # 암만 
  infra = 0.2
}

province = {
  id = 1023 # 이르비드 
  infra = 0.4
}

province = {
  id = 1024 # 아즈 자르카 
  infra = -0.2
}

province = {
  id = 1025 # 마안 
  infra = 0.2
}

province = {
  id = 1028 # 알 아마라 
  infra = -0.1
}

province = {
  id = 1029 # 모술 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1030 # 카르발라 
  infra = -0.2
}

province = {
  id = 1031 # 안 나자프 
  infra = -0.1
}

province = {
  id = 1032 # 바스라 
  infra = -0.2
}

province = {
  id = 1033 # 엘 힐라 
  landfort = 4
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 1034 # 바그다드 
  infra = -0.2
}

province = {
  id = 1035 # 쿠트 
  infra = -0.1
  landfort = 4
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1036 # 키르쿠크 
  infra = -0.2
}

province = {
  id = 1037 # 안 나시리야 
  infra = -0.1
}

province = {
  id = 1048 # 메디나 
  infra = 0.4
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1049 # 메카 
  landfort = 2
}

province = {
  id = 1052 # 무스카트 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1055 # 아다나 
  infra = 0.2
}

province = {
  id = 1056 # 가지안테프 
  infra = 0.4
}

province = {
  id = 1059 # 시바스 
  infra = 0.1
}

province = {
  id = 1060 # 디야르바키르 
  infra = -0.1
}

province = {
  id = 1061 # 말라티아 
  infra = 0.1
}

province = {
  id = 1062 # 하카리 
  infra = 0.1
}

province = {
  id = 1063 # 에르주룸 
  infra = 0.1
  landfort = 4
}

province = {
  id = 1064 # 엘라즈으 
  infra = 0.1
}

province = {
  id = 1065 # 카라뷔크 
  infra = 0.1
}

province = {
  id = 1066 # 삼순 
  infra = 0.1
}

province = {
  id = 1067 # 트라브존 
  infra = 0.1
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 1068 # 종굴다크 
  infra = -0.1
}

province = {
  id = 1071 # 에스키셰히르 
  infra = 0.2
}

province = {
  id = 1072 # 크륵칼레 
  infra = -0.1
}

province = {
  id = 1074 # 코니아 
  infra = 0.2
}

province = {
  id = 1075 # 앙카라 
  anti_air = 4
}

province = {
  id = 1076 # 이즈미트 
  infra = 0.4
  anti_air = 4
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1077 # 스미르나 
  infra = -0.1
  air_base = { size = 3 current_size = 3 }
}

province = {
  id = 1078 # 부르사 
  infra = 0.2
}

province = {
  id = 1079 # 데니즐리 
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1083 # 타브리즈 
  air_base = { size = 1 current_size = 1 }
}

province = {
  id = 1084 # 케르만샤 
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1091 # 가메룬 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1097 # 아슈하바트 
  ic = -1
}

province = {
  id = 1098 # 메르브 
  ic = -1
}

province = {
  id = 1099 # 사마르칸트 
  ic = -1
}

province = {
  id = 1100 # 부하라 
  ic = -1
}

province = {
  id = 1113 # 우랄스크 
  ic = -1
}

province = {
  id = 1118 # 포트 알렉산드로프스키 
  ic = -1
}

province = {
  id = 1119 # 키질 
  ic = -4
}

province = {
  id = 1128 # 니즈니 타길 
  ic = -1
}

province = {
  id = 1129 # 보르쿠타 
  ic = -1
}

province = {
  id = 1130 # 베레즈니키 
  ic = -1
}

province = {
  id = 1131 # 우파 
  ic = -1
}

province = {
  id = 1132 # 첼랴빈스크 
  ic = -1
}

province = {
  id = 1134 # 오렌부르크 
  ic = -1
}

province = {
  id = 1137 # 쿠르간 
  ic = -1
}

province = {
  id = 1138 # 옴스크 
  ic = -1
}

province = {
  id = 1140 # 바르나울 
  ic = -1
}

province = {
  id = 1142 # 노보시비르스크 
  ic = -1
}

province = {
  id = 1144 # 케메로보 
  ic = -1
}

province = {
  id = 1145 # 쿠즈네츠키 
  ic = -1
}

province = {
  id = 1148 # 톰스크 
  ic = -1
}

province = {
  id = 1151 # 스베르들롭스크 
  ic = -2
}

province = {
  id = 1156 # 크라스노야르스크 
  ic = -1
}

province = {
  id = 1162 # 이르쿠츠크 
  ic = -1
}

province = {
  id = 1170 # 네베르 
  ic = -1
}

province = {
  id = 1172 # 예루살렘 
  infra = -0.1
  landfort = 4
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1191 # 블라디보스토크 
  landfort = 1
  coastalfort = 3
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1199 # 하얼빈 
  ic = -1
}

province = {
  id = 1202 # 자무쓰 
  ic = -1
}

province = {
  id = 1215 # 푸순 
  ic = -1
}

province = {
  id = 1219 # 포트 아서 
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 1220 # 단동 
  ic = -1
}

province = {
  id = 1223 # 원산 
  ic = -1
}

province = {
  id = 1227 # 함흥 
  ic = -1
}

province = {
  id = 1230 # 광주 
  ic = -1
}

province = {
  id = 1232 # 부산 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1233 # 춘천 
  ic = -3
}

province = {
  id = 1252 # 타이위안 
  ic = -1
}

province = {
  id = 1259 # 옌안 
  ic = -2
}

province = {
  id = 1264 # 란저우 
  ic = -1
}

province = {
  id = 1279 # 카슈가르 
  ic = -1
}

province = {
  id = 1281 # 우루무치 
  ic = -2
}

province = {
  id = 1301 # 푸링 
  ic = -1
}

province = {
  id = 1308 # 창사 
  ic = -2
}

province = {
  id = 1328 # 칭다오 
  coastalfort = 3
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1330 # 지난 
  ic = -1
}

province = {
  id = 1338 # 상하이 
  ic = -2
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1352 # 난창 
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1353 # 주장 
  ic = -1
}

province = {
  id = 1361 # 가오슝 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1370 # 루펑 
  ic = -1
}

province = {
  id = 1371 # 홍콩 
  coastalfort = 1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1372 # 마카오 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1375 # 산터우 
  ic = -1
}

province = {
  id = 1379 # 난닝 
  ic = -1
}

province = {
  id = 1390 # 쿤밍 
  ic = -3
}

province = {
  id = 1395 # 하노이 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1399 # 사이공 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1415 # 랑군 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1424 # 나콘 사완 
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 1432 # 싱가포르 
  coastalfort = 3
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1511 # 콜롬보 
  coastalfort = 3
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1517 # 뭄바이 
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 1533 # 카라치 
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 1542 # 도요하라 
  ic = -1
}

province = {
  id = 1543 # 샤나 
  ic = -1
}

province = {
  id = 1544 # 구시로 
  ic = -1
}

province = {
  id = 1545 # 삿포로 
  ic = -2
}

province = {
  id = 1549 # 센다이 
  ic = -1
}

province = {
  id = 1550 # 요코하마 
  ic = -1
}

province = {
  id = 1551 # 니가타 
  ic = -1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1552 # 도쿄 
  ic = 1
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1553 # 오사카 
  ic = -1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1554 # 히로시마 
  ic = -1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1555 # 고베 
  ic = -1
}

province = {
  id = 1556 # 가나자와 
  ic = -1
}

province = {
  id = 1557 # 나고야 
  ic = -1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1558 # 교토 
  ic = -1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1559 # 마츠야마 
  ic = -1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1560 # 나가사키 
  ic = -1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1561 # 가고시마 
  ic = -1
}

province = {
  id = 1562 # 아마미 
  ic = -1
}

province = {
  id = 1563 # 오키나와 남부 
  ic = -1
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 1586 # 누벨 칼레도니 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1607 # 포트 모르즈비 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1611 # 말레 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1617 # 딜리 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1638 # 벵쿨루 
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 1648 # 트질레곤 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1653 # 수라바야 
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 1659 # 마나도 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1661 # 이오지마 
  ic = -1
}

province = {
  id = 1662 # 치치지마 
  ic = -1
}

province = {
  id = 1663 # 모토야마 
  ic = -1
}

province = {
  id = 1664 # 수리바치 산 
  ic = -2
}

province = {
  id = 1665 # 포나페 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1672 # 미나미 토리시마 
  ic = -1
}

province = {
  id = 1673 # 웨이크 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1675 # 에니웨톡 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1676 # 콰잘레인 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1683 # 괌 
  ic = -1
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1694 # 콜리 
  coastalfort = 1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1697 # 다윈 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1704 # 브리즈번 
  coastalfort = 1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1705 # 시드니 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1708 # 멜버른 
  coastalfort = 2
}

province = {
  id = 1721 # 웰링턴 
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 1726 # 라바울 
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 1734 # 진주만 
  coastalfort = 1
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 1773 # 버뮤다 제도 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1776 # 아바나 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1778 # 관타나모 만 해군 기지 
  coastalfort = 1
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 1780 # 시우다드 트루히요 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1781 # 포르-토-프랭스 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 1785 # 루이스턴 
  ic = -1
}

province = {
  id = 1788 # 하트퍼드 
  ic = -3
}

province = {
  id = 1789 # 보스턴 
  ic = -4
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1791 # 버팔로 
  ic = -3
}

province = {
  id = 1792 # 시러큐스 
  ic = -2
}

province = {
  id = 1793 # 올버니 
  ic = -2
}

province = {
  id = 1795 # 뉴욕 
  ic = -7
  coastalfort = 3
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1796 # 프로비던스 
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 1797 # 뉴어크 
  ic = -2
}

province = {
  id = 1801 # 해리스버그 
  ic = -2
}

province = {
  id = 1805 # 필라델피아 
  ic = -6
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 1806 # 피츠버그 
  ic = -4
}

province = {
  id = 1808 # 볼티모어 
  ic = -4
  coastalfort = 2
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 1809 # 워싱턴 
  coastalfort = 1
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1812 # 노퍽 
  ic = -2
  coastalfort = 1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1813 # 리치먼드 
  ic = -2
}

province = {
  id = 1821 # 콜럼버스 
  ic = -2
}

province = {
  id = 1823 # 신시내티 
  ic = -4
}

province = {
  id = 1824 # 이리 
  ic = -1
}

province = {
  id = 1825 # 클리블랜드 
  ic = -6
}

province = {
  id = 1826 # 포트 웨인 
  ic = -2
}

province = {
  id = 1828 # 인디애나폴리스 
  ic = -2
}

province = {
  id = 1832 # 시카고 
  ic = -7
}

province = {
  id = 1833 # 세인트 루이스 
  ic = -4
}

province = {
  id = 1839 # 밀워키 
  ic = -4
}

province = {
  id = 1844 # 플린트 
  ic = -3
}

province = {
  id = 1845 # 디트로이트 
  ic = -5
}

province = {
  id = 1847 # 미니애폴리스 
  ic = -2
}

province = {
  id = 1874 # 시애틀 
  ic = -3
  coastalfort = 3
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1878 # 포틀랜드 
  ic = -3
}

province = {
  id = 1879 # 유진 
  ic = -1
}

province = {
  id = 1886 # 샌디에이고 
  ic = -3
  coastalfort = 1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1887 # 로스앤젤레스 
  ic = -3
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 1889 # 샌프란시스코 
  ic = -2
  coastalfort = 1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1890 # 유레카 
  ic = -1
}

province = {
  id = 1896 # 솔트레이크 시티 
  ic = -3
}

province = {
  id = 1908 # 덴버 
  ic = -2
}

province = {
  id = 1914 # 캔자스 시티 
  ic = -1
}

province = {
  id = 1922 # 코퍼스 크리스티 
  ic = -1
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 1924 # 댈러스 
  ic = -4
}

province = {
  id = 1925 # 오스틴 
  ic = -1
}

province = {
  id = 1926 # 샌안토니오 
  ic = -1
  air_base = { size = 2 current_size = 2 }
}

province = {
  id = 1928 # 휴스턴 
  ic = -6
  coastalfort = 1
}

province = {
  id = 1931 # 뉴올리언스 
  ic = -3
  coastalfort = 1
}

province = {
  id = 1940 # 멤피스 
  ic = -4
}

province = {
  id = 1942 # 녹스빌 
  ic = -2
}

province = {
  id = 1948 # 탬파 
  coastalfort = 1
}

province = {
  id = 1953 # 마이애미 
  coastalfort = 1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 1955 # 애틀랜타 
  ic = -2
}

province = {
  id = 1960 # 찰스턴 
  coastalfort = 1
}

province = {
  id = 1970 # 오악사카 데 후아레스 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 1986 # 바랑키야 
  naval_base = { size = 2 current_size = 2 }
}

province = {
  id = 1988 # 마라카이보 
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 2016 # 리마 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 2023 # 산티아고 데 칠레 
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 2040 # 산티아고 데 과야킬 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 2045 # 말비나스 제도 
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 2048 # 라 플라타 
  naval_base = { size = 8 current_size = 5 }
}

province = {
  id = 2050 # 부에노스 아이레스 
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 2052 # 몬테비데오 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 2058 # 포르투 알레그리 
  naval_base = { size = 8 current_size = 8 }
}

province = {
  id = 2059 # 상 파울루 
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 2075 # 리우 데 자네이루 
  naval_base = { size = 6 current_size = 6 }
}

province = {
  id = 2078 # 시우다드 데 파나마 
  naval_base = { size = 3 current_size = 3 }
}

province = {
  id = 2079 # 산 살바도르 
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 2080 # 마나과 
  naval_base = { size = 1 current_size = 1 }
}

province = {
  id = 2081 # 산 호세 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2085 # 테구시갈파 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 2088 # 시우다드 데 과테말라 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 2089 # 밴쿠버 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2090 # 빅토리아 
  coastalfort = 1
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2117 # 퀘벡 
  landfort = 6
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2132 # 핼리팩스 
  coastalfort = 6
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2137 # 세인트 존스 
  naval_base = { size = 10 current_size = 10 }
}

province = {
  id = 2142 # 앵커리지 
  naval_base = { size = 4 current_size = 4 }
}

province = {
  id = 2152 # 말뫼 
  coastalfort = 2
}

province = {
  id = 2153 # 예테보리 
  landfort = 1
  coastalfort = 1
  naval_base = { size = 5 current_size = 5 }
}

province = {
  id = 2159 # 스톡홀름 
  coastalfort = 2
  naval_base = { size = 7 current_size = 7 }
}

province = {
  id = 2166 # 룰레아 
  landfort = 2
}

province = {
  id = 2171 # 카불 
  landfort = 4
}

province = {
  id = 2172 # 헤라트 
  landfort = 2
}

