province = {
  id = 34 # 더블린 
  supplypool = 2
}
province = {
  id = 348 # 지브롤터 
  supplypool = 2
}
province = {
  id = 429 # 몰타 
  supplypool = 2
}
province = {
  id = 435 # 사사리 
  supplypool = 2
}
province = {
  id = 475 # 팔마 데 마요르카 
  supplypool = 2
}
province = {
  id = 715 # 탕헤르 
  supplypool = 2
}
province = {
  id = 728 # 오랑 
  supplypool = 20
}
province = {
  id = 765 # 투브루크 
  supplypool = 3
  oilpool = 3
}
province = {
  id = 789 # 알렉산드리아 
  supplypool = 5
  oilpool = 5
}
province = {
  id = 815 # 마사와 
  supplypool = 2
}
province = {
  id = 836 # 모가디슈 
  supplypool = 2
}
province = {
  id = 850 # 다르 에스 살람 
  supplypool = 10
}
province = {
  id = 855 # 로렌소 마르케스 
  supplypool = 5
}
province = {
  id = 883 # 뤼데리츠 
  supplypool = 5
}
province = {
  id = 889 # 발보아 
  supplypool = 5
  oilpool = 5
}
province = {
  id = 894 # 마타디 
  supplypool = 3
}
province = {
  id = 895 # 루안다 
  supplypool = 5
}
province = {
  id = 909 # 야운데 
  supplypool = 5
}
province = {
  id = 915 # 리브르빌 
  supplypool = 20
}
province = {
  id = 929 # 라고스 
  supplypool = 2
}
province = {
  id = 950 # 로메 
  supplypool = 5
}
province = {
  id = 956 # 아크라 
  supplypool = 2
}
province = {
  id = 963 # 비사우 
  supplypool = 5
}
province = {
  id = 964 # 프리타운 
  supplypool = 2
}
province = {
  id = 990 # 라스팔마스 데 그랑 카나리아 
  supplypool = 2
}
province = {
  id = 994 # 마데이라 
  supplypool = 5
}
province = {
  id = 995 # 아조레스 제도 
  supplypool = 5
}
province = {
  id = 997 # 포트 루이스 
  supplypool = 2
}
province = {
  id = 1002 # 타마타베 
  supplypool = 2
}
province = {
  id = 1053 # 아덴 
  supplypool = 2
}
province = {
  id = 1219 # 포트 아서 
  supplypool = 2
}
province = {
  id = 1232 # 부산 
  supplypool = 3
}
province = {
  id = 1328 # 칭다오 
  supplypool = 10
  oilpool = 10
}
province = {
  id = 1331 # 옌타이 
  supplypool = 2
}
province = {
  id = 1362 # 타이페이 
  supplypool = 2
}
province = {
  id = 1371 # 홍콩 
  supplypool = 2
}
province = {
  id = 1372 # 마카오 
  supplypool = 5
}
province = {
  id = 1432 # 싱가포르 
  supplypool = 2
}
province = {
  id = 1511 # 콜롬보 
  supplypool = 2
  oilpool = 2
}
province = {
  id = 1513 # 빤짐 
  supplypool = 5
}
province = {
  id = 1542 # 도요하라 
  supplypool = 2
}
province = {
  id = 1563 # 오키나와 남부 
  supplypool = 2
}
province = {
  id = 1565 # 마닐라 
  supplypool = 2
}
province = {
  id = 1586 # 누벨 칼레도니 
  supplypool = 2
}
province = {
  id = 1617 # 딜리 
  supplypool = 5
}
province = {
  id = 1621 # 부루 
  supplypool = 10
}
province = {
  id = 1633 # 반자르마신 
  supplypool = 10
}
province = {
  id = 1638 # 벵쿨루 
  supplypool = 10
}
province = {
  id = 1659 # 마나도 
  supplypool = 10
}
province = {
  id = 1710 # 호바트 
  supplypool = 2
}
province = {
  id = 1726 # 라바울 
  supplypool = 5
  oilpool = 5
}
province = {
  id = 1734 # 진주만 
  supplypool = 5
  oilpool = 5
}
province = {
  id = 1765 # 푸에르토 리코 
  supplypool = 2
}
province = {
  id = 1773 # 버뮤다 제도 
  supplypool = 2
}
province = {
  id = 1968 # 베라크루스 
  supplypool = 2
}
province = {
  id = 2045 # 말비나스 제도 
  supplypool = 2
  oilpool = 2
}
province = {
  id = 2142 # 앵커리지 
  supplypool = 2
}
province = {
  id = 2156 # 비스뷔 
  supplypool = 2
}
