 
 ############################### 
 # Victory points distribution #
 ############################### 
  
 # United States : 44 
 province = { id = 1809 points = 3 } # Washington D.C. 
 province = { id = 1795 points = 3 } # New York 
 province = { id = 1789 points = 2 } # Boston 
 province = { id = 1805 points = 2 } # Philadelphia 
 province = { id = 1845 points = 2 } # Detroit 
 province = { id = 1832 points = 2 } # Chicago 
 province = { id = 1808 points = 2 } # Baltimore
 province = { id = 1791 points = 1 } # Buffalo
 province = { id = 1806 points = 1 } # Pittsburgh 
 province = { id = 1734 points = 1 } # Pearl Harbour 
 province = { id = 1931 points = 2 } # New Orleans 
 province = { id = 1908 points = 1 } # Denver 
 province = { id = 1924 points = 1 } # Dallas 
 province = { id = 1928 points = 1 } # Houston 
 province = { id = 889 points = 2 } # Panamá 
 province = { id = 1812 points = 1 } # Norfolk
 province = { id = 1886 points = 1 } # San Diego 
 province = { id = 1887 points = 1 } # Los Angeles 
 province = { id = 1889 points = 2 } # San Francisco 
 province = { id = 1819 points = 1 } # Louisville
 province = { id = 1823 points = 1 } # Cincinnati
 province = { id = 1825 points = 1 } # Cleveland
 province = { id = 1833 points = 1 } # Saint Louis
 province = { id = 1839 points = 1 } # Milwaukee
 province = { id = 1847 points = 1 } # Minneapolis
 province = { id = 1878 points = 1 } # Portland
 province = { id = 1874 points = 1 } # Seattle 
 province = { id = 1896 points = 1 } # Salt Lake City
 province = { id = 1955 points = 1 } # Atlanta
 province = { id = 1960 points = 1 } # Charleston
 province = { id = 1565 points = 1 } # Manila
 province = { id = 1579 points = 1 } # Davao
  
 # Germany : 48 
 province = { id = 163 points = 5 } # Berlin 
 province = { id = 179 points = 2 } # Munich 
 province = { id = 104 points = 1 } # Metz
 province = { id = 131 points = 2 } # Cologne 
 province = { id = 154 points = 2 } # Hamburg 
 province = { id = 145 points = 3 } # Essen 
 province = { id = 184 points = 2 } # Königsberg
 province = { id = 107 points = 2 } # Strasbourg
 province = { id = 134 points = 2 } # Stuttgart
 province = { id = 138 points = 2 } # Frankfurt am Main
 province = { id = 142 points = 2 } # Düsseldorf
 province = { id = 173 points = 2 } # Dresden
 province = { id = 105 points = 1 } # Colmar
 province = { id = 127 points = 1 } # Saarbrück
 province = { id = 128 points = 1 } # Trier
 province = { id = 130 points = 1 } # Mainz
 province = { id = 132 points = 1 } # Freiburg am Breisgau
 province = { id = 146 points = 1 } # Hannover
 province = { id = 147 points = 1 } # Wilhelmshaven
 province = { id = 148 points = 1 } # Bremen
 province = { id = 152 points = 1 } # Kiel
 province = { id = 158 points = 1 } # Stettin
 province = { id = 167 points = 1 } # Breslau
 province = { id = 170 points = 1 } # Leipzig
 province = { id = 171 points = 1 } # Erfurt
 province = { id = 181 points = 1 } # Danzig
 province = { id = 222 points = 1 } # Thorn
 province = { id = 224 points = 1 } # Posen
 province = { id = 225 points = 1 } # Bromberg
 province = { id = 850 points = 1 } # Dar Es Salaam
 province = { id = 883 points = 1 } # Lüderitz
 province = { id = 909 points = 1 } # Yaoundé
 province = { id = 950 points = 1 } # Lomé
 
 # United Kingdom : 33 
 province = { id = 29 points = 3 } # London 
 province = { id = 348 points = 2 } # Gibraltar 
 province = { id = 900 points = 2 } # Suez 
 province = { id = 18 points = 1 } # Sheffield 
 province = { id = 429 points = 1 } # Malta 
 province = { id = 11 points = 1 } # Glasgow 
 province = { id = 1432 points = 1 } # Singapore 
 province = { id = 5 points = 1 } # Scapa Flow
 province = { id = 12 points = 1 } # Edinburgh
 province = { id = 17 points = 2 } # Manchester
 province = { id = 22 points = 1 } # Cardiff
 province = { id = 24 points = 2 } # Birmingham
 province = { id = 26 points = 1 } # Dover
 province = { id = 27 points = 1 } # Portsmouth
 province = { id = 31 points = 1 } # Cork
 province = { id = 34 points = 1 } # Dublin
 province = { id = 36 points = 2 } # Belfast
 province = { id = 787 points = 1 } # Cairo
 province = { id = 789 points = 1 } # Alexandria
 province = { id = 810 points = 1 } # Khartum
 province = { id = 842 points = 1 } # Monbasa
 province = { id = 867 points = 1 } # Salisbury
 province = { id = 929 points = 1 } # Lagos
 province = { id = 964 points = 1 } # Freetown
 province = { id = 1371 points = 1 } # Hong Kong
 province = { id = 1511 points = 1 } # Colombo

  
 # Russia : 61
 province = { id = 572 points = 3 } # Moscow 
 province = { id = 553 points = 3 } # Petrograd
 province = { id = 663 points = 1 } # Tsaritsyn
 province = { id = 535 points = 1 } # Murmansk 
 province = { id = 599 points = 1 } # Minsk 
 province = { id = 617 points = 2 } # Kiev 
 province = { id = 641 points = 1 } # Sevastopol 
 province = { id = 1191 points = 1 } # Vladivostok 
 province = { id = 1138 points = 1 } # Omsk 
 province = { id = 713 points = 1 } # Baku 
 province = { id = 1142 points = 1 } # Novosibirsk 
 province = { id = 264  points = 2 } # Riga
 province = { id = 270  points = 1 } # Tallinn 
 province = { id = 223  points = 1 } # Lodz
 province = { id = 232  points = 2 } # Warsaw
 province = { id = 243  points = 1 } # Lublin
 province = { id = 247  points = 1 } # Brest-Litovsk
 province = { id = 258  points = 1 } # Wilno
 province = { id = 304  points = 1 } # Chisinau
 province = { id = 386  points = 1 } # Kars
 province = { id = 520  points = 1 } # Oulu
 province = { id = 525  points = 1 } # Helsinki
 province = { id = 542  points = 1 } # Arkhangelsk
 province = { id = 560  points = 1 } # Novgorod
 province = { id = 584  points = 1 } # Tula
 province = { id = 589  points = 1 } # Smolensk
 province = { id = 590  points = 1 } # Vitebsk
 province = { id = 600  points = 1 } # Mogilev
 province = { id = 624  points = 1 } # Kherson
 province = { id = 626  points = 1 } # Odessa
 province = { id = 636  points = 1 } # Kharkov
 province = { id = 644  points = 1 } # Rostov
 province = { id = 654  points = 1 } # Voronej
 province = { id = 668  points = 1 } # Samara
 province = { id = 672  points = 1 } # Kazan
 province = { id = 680  points = 1 } # Nijni Novgorod
 province = { id = 687  points = 1 } # Perm
 province = { id = 691  points = 1 } # Krasnodar
 province = { id = 703  points = 1 } # Vladikavkaz
 province = { id = 706  points = 1 } # Astrakhan
 province = { id = 709  points = 1 } # Tiflis
 province = { id = 711  points = 1 } # Yerevan
 province = { id = 1099  points = 1 } # Samarkand
 province = { id = 1103  points = 1 } # Tashkent
 province = { id = 1131  points = 1 } # Ufa
 province = { id = 1132  points = 1 } # Chelyabinsk
 province = { id = 1134  points = 1 } # Orenburg
 province = { id = 1151  points = 1 } # Yekaterinburg
 province = { id = 1156  points = 1 } # Krasnoyarsk
 province = { id = 1162  points = 1 } # Irkutsk
 province = { id = 1169  points = 1 } # Chita
 province = { id = 1176  points = 1 } # Blagoveshchensk
 province = { id = 1189  points = 1 } # Nikolayevsk na Amure
 province = { id = 1190  points = 1 } # Khabarovsk
  
 # Japan : 12 
 province = { id = 1552 points = 2 } # Tokyo 
 province = { id = 1545 points = 1 } # Sapporo
 province = { id = 1557 points = 1 } # Nagoya 
 province = { id = 1553 points = 1 } # Osaka 
 province = { id = 1554 points = 1 } # Hiroshima
 province = { id = 1558 points = 1 } # Kyoto
 province = { id = 1228 points = 1 } # Seoul 
 province = { id = 1221 points = 1 } # Pyongyang 
 province = { id = 1362 points = 1 } # Taiyuan 
 province = { id = 1232 points = 1 } # Busan
 province = { id = 1561 points = 1 } # Kagoshima

# France : 39
 province = { id = 55 points = 5 } # Paris
 province = { id = 100 points = 2 } # Verdun
 province = { id = 37 points = 1 } # Brest
 province = { id = 40 points = 1 } # St-Nazaire
 province = { id = 68 points = 1 } # Bordeaux
 province = { id = 89 points = 2 } # Marseille
 province = { id = 52 points = 3 } # Lille
 province = { id = 43 points = 1 } # Cherbourg
 province = { id = 45 points = 1 } # Le Havre
 province = { id = 49 points = 1 } # Calais
 province = { id = 50 points = 1 } # Amiens
 province = { id = 61 points = 1 } # Tours
 province = { id = 66 points = 1 } # Orléans
 province = { id = 77 points = 1 } # Toulouse
 province = { id = 85 points = 2 } # Lyon
 province = { id = 86 points = 1 } # Toulon
 province = { id = 90 points = 1 } # Grenoble
 province = { id = 97 points = 1 } # Belfort
 province = { id = 99 points = 1 } # Reims
 province = { id = 106 points = 2 } # Nancy
 province = { id = 727 points = 1 } # Algiers
 province = { id = 718 points = 1 } # Casablanca 
 province = { id = 747 points = 1 } # Tunis 
 province = { id = 728 points = 1 } # Oran
 province = { id = 734 points = 1 } # Constantine
 province = { id = 915 points = 1 } # Libreville
 province = { id = 962 points = 1 } # Abidjan
 province = { id = 978 points = 1 } # Dakar
 province = { id = 1001 points = 1 } # Tananarive

 # Indochinese Union : 2
 province = { id = 1399 points = 1 } # Saigon
 province = { id = 1395 points = 1 } # Hanoi
  
 # China : 12
 province = { id = 1337 points = 2 } # Nanjing 
 province = { id = 1299 points = 2 } # Chongqing 
 province = { id = 1247 points = 1 } # Beiping 
 province = { id = 1338 points = 1 } # Shanghai 
 province = { id = 1354 points = 1 } # Ganzhou 
 province = { id = 1260 points = 1 } # Yan'an 
 province = { id = 1390 points = 1 } # Kunming 
 province = { id = 1369 points = 1 } # Guangzhou 
 province = { id = 1297 points = 1 } # Chengdu
 province = { id = 1283 points = 1 } # Ge'ermu
  
 # Italy : 22
 province = { id = 407 points = 3 } # Milan 
 province = { id = 750 points = 1 } # Tripoli 
 province = { id = 774 points = 1 } # Al Jawf 
 province = { id = 419 points = 3 } # Rome 
 province = { id = 421 points = 2 } # Naples 
 province = { id = 422 points = 1 } # Taranto 
 province = { id = 430 points = 1 } # Palermo 
 province = { id = 761 points = 1 } # Benghazi
 province = { id = 396 points = 1 } # Genoa 
 province = { id = 398 points = 1 } # Torino
 province = { id = 400 points = 2 } # Venice
 province = { id = 405 points = 1 } # Udine
 province = { id = 410 points = 1 } # Florence
 province = { id = 426 points = 1 } # Bari
 province = { id = 434 points = 1 } # Cagliari
 province = { id = 817 points = 1 } # Asmara
 province = { id = 836 points = 1 } # Mogadiscio
  
 # India : 14
 province = { id = 1053 points = 1 } # Aden
 province = { id = 1415 points = 1 } # Rangoon 
 province = { id = 1517 points = 1 } # Bombay 
 province = { id = 1447 points = 1 } # Calcutta 
 province = { id = 1459 points = 1 } # Delhi 
 province = { id = 1533 points = 1 } # Karachi 
 province = { id = 1487 points = 1 } # Hyderabad 
 province = { id = 1445 points = 1 } # Dhaka
 province = { id = 1461 points = 1 } # Lucknow
 province = { id = 1480 points = 1 } # Bhopal
 province = { id = 1500 points = 1 } # Madras
 province = { id = 1518 points = 1 } # Ahmadabad
 province = { id = 1530 points = 1 } # Lahore
 province = { id = 1537 points = 1 } # Peshawar
  
 # Ottoman Empire : 17
 province = { id = 385 points = 1 } # Adrianople
 province = { id = 384 points = 2 } # Gallipoli
 province = { id = 409 points = 3 } # Constantinople
 province = { id = 1034 points = 1 } # Baghdad 
 province = { id = 1019 points = 1 } # Beirut
 province = { id = 1016 points = 1 } # Damascus
 province = { id = 1021 points = 1 } # Aleppo
 province = { id = 1029 points = 1 } # Mosul
 province = { id = 1032 points = 1 } # Basrah
 province = { id = 1063 points = 1 } # Erzurum
 province = { id = 1067 points = 1 } # Trabzon
 province = { id = 1075 points = 1 } # Ankara
 province = { id = 1077 points = 1 } # Smyrna
 province = { id = 1172 points = 1 } # Jerusalem

 # Hejaz : 2
 province = { id = 1049 points = 1 } # Mecca 
 province = { id = 1048 points = 1 } # Medina

 # Persia : 6
 province = { id = 1085 points = 1 } # Tehran
 province = { id = 1086 points = 1 } # Esfahan
 province = { id = 1083 points = 1 } # Tabriz
 province = { id = 1092 points = 1 } # Mashhad
 province = { id = 1089 points = 1 } # Ahvaz
 province = { id = 1091 points = 1 } # Gameroon

 # Austria-Hungary : 24
 province = { id = 235 points = 1 } # Cracow 
 province = { id = 189 points = 1 } # Innsbrück
 province = { id = 190 points = 1 } # Graz
 province = { id = 242 points = 1 } # Lwow
 province = { id = 352 points = 1 } # Zagreb 
 province = { id = 355 points = 1 } # Sarajevo 
 province = { id = 195 points = 3 } # Vienna 
 province = { id = 196 points = 1 } # Brunn
 province = { id = 207 points = 2 } # Prague
 province = { id = 208 points = 1 } # Bratislava
 province = { id = 284 points = 2 } # Budapest 
 province = { id = 239 points = 1 } # Przemysl
 province = { id = 285 points = 1 } # Temeszvar
 province = { id = 288 points = 1 } # Koloszvar
 province = { id = 291 points = 1 } # Nagyszeben
 province = { id = 343 points = 1 } # Dubrovnik
 province = { id = 349 points = 1 } # Laibach
 province = { id = 401 points = 1 } # Trient
 province = { id = 404 points = 1 } # Trieste
 province = { id = 406 points = 1 } # Pola

 # Spain : 8 
 province = { id = 460 points = 2 } # Madrid 
 province = { id = 474 points = 1 } # Seville 
 province = { id = 440 points = 2 } # Barcelona 
 province = { id = 464 points = 1 } # Valencia 
 province = { id = 441 points = 1 } # La Coruna 
 province = { id = 442 points = 1 } # Zaragoza
 province = { id = 443 points = 1 } # Bilbao
  
 # Australia : 6
 province = { id = 1690 points = 1 } # Perth
 province = { id = 1697 points = 1 } # Darwin
 province = { id = 1705 points = 1 } # Sidney
 province = { id = 1704 points = 1 } # Brisbane
 province = { id = 1708 points = 1 } # Melbourne
 province = { id = 1712 points = 1 } # Adelaide
  
 # Canada : 7
 province = { id = 2106 points = 1 } # Winnipeg 
 province = { id = 2119 points = 1 } # Montréal 
 province = { id = 2108 points = 1 } # Ottawa 
 province = { id = 2111 points = 1 } # Toronto 
 province = { id = 2089 points = 1 } # Vancouver
 province = { id = 2103 points = 1 } # Edmonton
 province = { id = 2117 points = 1 } # Québec
 province = { id = 2132 points = 1 } # Halifax

 # Norway : 4 
 province = { id = 497 points = 1 } # Tromso
 province = { id = 483 points = 1 } # Oslo 
 province = { id = 493 points = 1 } # Trondheim & Bergen 
 province = { id = 488 points = 1 } 
  
 # Argentina : 6 
 province = { id = 2050 points = 1 } # Buenos Aires 
 province = { id = 2048 points = 1 } # La Plata 
 province = { id = 2054 points = 1 } # Cordoba 
 province = { id = 2049 points = 1 } # Corrientes
 province = { id = 2028 points = 1 } # Mendoza
 province = { id = 2037 points = 1 } # Comodoro Rivadavia

 # Belgium : 7
 province = { id = 115 points = 2 } # Antwerp 
 province = { id = 116 points = 2 } # Brussels 
 province = { id = 114 points = 1 } # Bruges
 province = { id = 899 points = 1 } # Leopoldville 
 province = { id = 108 points = 1 } # Liège

 # Brazil : 7 
 province = { id = 2059 points = 1 } # Sao Paulo 
 province = { id = 2075 points = 1 } # Rio de Janeiro 
 province = { id = 2076 points = 1 } # Belo Horizonte
 province = { id = 2005 points = 1 } # Manaus
 province = { id = 2058 points = 1 } # Porto Alegre
 province = { id = 2068 points = 1 } # Belem
 province = { id = 2071 points = 1 } # Recife

 # Sweden : 5
 province = { id = 2159 points = 1 } # Stockholm
 province = { id = 2152 points = 1 } # Malmö
 province = { id = 2153 points = 1 } # Gothenburg
 province = { id = 2160 points = 1 } # Orebro
 province = { id = 2166 points = 1 } # Lulea

 # Switzerland : 3 
 province = { id = 391 points = 1 } # Geneva 
 province = { id = 392 points = 1 } # Bern 
 province = { id = 389 points = 1 } # Zurich 

 # Serbia : 6
 province = { id = 338 points = 2 } # Belgrade 
 province = { id = 333 points = 1 } # Skopje
 province = { id = 330 points = 1 } # Nis
 province = { id = 329 points = 1 } # Pristina
 province = { id = 327 points = 1 } # Krisevac

 # Montenegro : 2
 province = { id = 332 points = 1 } # Cetinje
 province = { id = 335 points = 1 } # Prijepolje

 # Bulgaria : 6
 province = { id = 321 points = 2 } # Sofia  
 province = { id = 323 points = 1 } # Pleven
 province = { id = 324 points = 1 } # Plovdiv
 province = { id = 326 points = 1 } # Varna
 province = { id = 363 points = 1 } # Xanthi

 # Greece : 7 
 province = { id = 377 points = 2 } # Athens 
 province = { id = 382 points = 1 } # Iraklion 
 province = { id = 365 points = 1 } # Salonika
 province = { id = 367 points = 1 } # Ioannina
 province = { id = 368 points = 1 } # Larissa
 province = { id = 373 points = 1 } # Corinth

 # Mexico : 2
 province = { id = 1974 points = 1 } # Mexico city 
 province = { id = 1968 points = 1 } # Vera Cruz 

 # Netherlands : 5 
 province = { id = 122 points = 2 } # Amsterdam 
 province = { id = 125 points = 2 } # Rotterdam
 province = { id = 1999 points = 1 } # Paramaribo

 # Dutch East Indies : 8 
 province = { id = 1647 points = 1 } # Batavia 
 province = { id = 1622 points = 1 } # Ceram
 province = { id = 1632 points = 1 } # Balikpapan
 province = { id = 1636 points = 1 } # Palembang
 province = { id = 1642 points = 1 } # Medan
 province = { id = 1651 points = 1 } # Bandung
 province = { id = 1653 points = 1 } # Surabaya
 province = { id = 1657 points = 1 } # Makassar

 # Romania : 8
 province = { id = 316 points = 2 } # Bucharest 
 province = { id = 311 points = 1 } # Ploesti 
 province = { id = 297 points = 1 } # Iasi 
 province = { id = 298 points = 1 } # Galati
 province = { id = 307 points = 1 } # Dobrich
 province = { id = 310 points = 1 } # Constanta
 province = { id = 312 points = 1 } # Turnu Severin

 # Venezuela : 2
 province = { id = 1993 points = 1 } # Caracas 
 province = { id = 1988 points = 1 } # Maracaibo

 # Colombia : 3
 province = { id = 1991 points = 1 } # Bogota 
 province = { id = 1985 points = 1 } # Cali
 province = { id = 1990 points = 1 } # Cucuta

 # Ethiopia : 1
 province = { id = 825 points = 1 } # Addis Abeba 

 # New Zealand : 3
 province = { id = 1721 points = 1 } # Wellington 
 province = { id = 1720 points = 1 } # Auckland
 province = { id = 1723 points = 1 } # Dunedin

 # Portugal : 5
 province = { id = 476 points = 1 } # Lisbon 
 province = { id = 478 points = 1 } # Beja
 province = { id = 481 points = 1 } # Porto
 province = { id = 855 points = 1 } # Lourenço Marques
 province = { id = 895 points = 1 } # Luanda

 # Siam : 1
 province = { id = 1423 points = 1 } # Bangkok 

 # South Africa : 3
 province = { id = 880 points = 1 } # Cape Town 
 province = { id = 873 points = 1 } # Pretoria
 province = { id = 876 points = 1 } # Johannesburg 

 # Uruguay : 1
 province = { id = 2052 points = 1 } # Montevideo 

 # Luxembourg : 1 
 province = { id = 109 points = 1 } # Luxembourg 
 
 # Albania : 1 
 province = { id = 359 points = 1 } # Tirana

 # Afghanistan : 4
 province = { id = 2169 points = 1 } # Kandahar
 province = { id = 2170 points = 1 } # Jalalabad
 province = { id = 2171 points = 1 } # Kabul
 province = { id = 2172 points = 1 } # Herat

 # Bolivia : 2
 province = { id = 2020 points = 1 } # La Paz
 province = { id = 2021 points = 1 } # Sucre

 # Chile : 4
 province = { id = 2022 points = 1 } # Valparaiso
 province = { id = 2023 points = 1 } # Santiago
 province = { id = 2024 points = 1 } # Iquique
 province = { id = 2031 points = 1 } # Temuco

 # Cuba : 2
 province = { id = 1776 points = 1 } # Havana
 province = { id = 1777 points = 1 } # Santiago de Cuba

 # Denmark : 2
 province = { id = 217 points = 1 } # Aalborg
 province = { id = 294 points = 1 } # Copenhagen

 # Ecuador : 2
 province = { id = 2040 points = 1 } # Guayaquil
 province = { id = 2042 points = 1 } # Quito

 # Newfoundland : 1
 province = { id = 2137 points = 1 } # St John's
 
 # Paraguay : 1
 province = { id = 2047 points = 1 } # Asuncion

 # Peru : 3
 province = { id = 2014 points = 1 } # Trujillo
 province = { id = 2015 points = 1 } # Cuzco
 province = { id = 2016 points = 1 } # Lima
