 
 ############################## 
 # Country definition for JAP # 
 ############################## 
  
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 {  tag                    = JAP 
	ai_settings	= { flags = { MOB1 = yes MOB2 = yes MOB3 = yes MOB4 = yes MOB5 = yes MOB6 = yes MOB7 = yes MOB8 = yes RES = yes } } 
	belligerence           = 100 
	capital                = 1552 
	manpower               = 2000 
	# Resource Reserves 
	energy                 = 5000 
	metal                  = 5000 
	rare_materials         = 30000 
	oil                    = 2000 
	supplies               = 5000 
	money                  = 120 
	transports             = 1220 
	escorts                = 81 
    
  diplomacy =
  { relation = { tag = AST value = -200 }
    relation = { tag = BEL value = -150 }
    relation = { tag = BUL value = 75 }
    relation = { tag = CHC value = -200 }
    relation = { tag = CHI value = -200 }
    relation = { tag = CHL value = 20 }
    relation = { tag = FIN value = 50 }
    relation =
    { tag        = GER
      value      = 135
      guaranteed = { day = 27 month = september year = 1940 }
    }
    relation =
    { tag        = HUN
      value      = 125
      guaranteed = { day = 20 month = november year = 1940 }
    }
    relation =
    { tag        = ITA
      value      = 125
      guaranteed = { day = 20 month = november year = 1940 }
    }
    relation = { tag = MAN value = 200 access = yes }
    relation = { tag = MEN value = 200 access = yes }
    relation =
    { tag        = ROM
      value      = 125
      guaranteed = { day = 27 month = september year = 1940 }
    }
    relation = { tag = SIA value = 150 }
    relation = { tag = FRA value = 50 }
    relation = { tag = USA value = -200 }
    relation = { tag = SIK value = -170 }
    relation = { tag = U03 value = 50 access = yes } 
  } 
   SpyInfo                = {  country = "JAP" NumberOfSpies = 9  } 
    
   # Sakhalin 
   nationalprovinces      = {  1543 1544 1545 1549 1551 1550 1556 1552 1557 1558 1553 1554 1559 1560 1561 1662 1661 1663 1664 1562 1563 1564 1672 1555 1542   
                              1541
         1547 1548 1546 
		 1228 1229 1230 1231 1232 1233 # South Korea 
		1221 1222 1223 1224 1225 1226 1227 # North Korea
		 1361 1362 1363 1364 # Taiwan 
                             } 
   ownedprovinces         = {  1543 1544 1545 1549 1551 1550 1556 1552 1557 1558 1553 1554 1559 1560 1561 1662 1661 1663 1664 1562 1563 1564 1672 1686 1685 1684 1668
        1670 1671 1665 1669 1667 1666 1674 1675 1676 1677 1681   1364 1225 1226 
  
         1227 1223 1221 1228 1233 1232 1231 1230 1224 1219  1542 1555 1361  
         1547 1548 1546 

 # Sakhalin 
 1222 1229 1363 
  
 #Japan in China        
 1362 1245

 #SE Asia
 1565 1566 1567 1568 1569 1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580
 1639 1642 1640 1635 1634 1637 1636 1641 1638 1647 1648 1646 1651 1650 1649 1654 1653 1652 1655 1656 1643 1645 1615 1616 1619 1644 1657 1658 1660 1659 1620 1621 1622
 1599 1600 1595 1601 1618 1598 1597 1596 1594 1633 1631 1628 1623 1627 1632 1629 1630 1617
 } 
  
   controlledprovinces    = {  1543 1544 1545 1549 1551 1550 1556 1552 1557 1558 1553 1554 1559 1560 1561 1662 1661 1663 1664 1562 1563 1564 1672 1686 1684 1668 
                              1670 1671 1665 1669 1667 1666 1674 1681   1364 1225 1226 
                              1227 1223 1221 1228 1233 1232 1231 1230 1224 1219  1542 1555 1361  
         1547 1548 1546 1362 1360 1375
 # Sakhalin 
 1222 1229 1363 
  
 #Japan in China        
 1245 1241 1247 1242 1243 1244 1251 1252 1248 1249 1250 1327 1328 1329 1330 1331 1332 1321 1323 1333 1334 1335 1339 1336 1340 1337 1338 1344 1342 1345 1343 1350 1353 
 1318 1369 1365 1370 1346 1348 1253 1254 1322 1367 1358 1308 1324 1319 1341 1320

 #SE Asia
 1565 1566 1567 1568 1569 1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580
 1639 1642 1640 1635 1634 1637 1636 1641 1638 1647 1648 1646 1651 1650 1649 1654 1653 1652 1655 1656 1643 1645 1615 1616 1619 1644 1657 1658 1660 1659 1620 1621 1622
 1599 1600 1601 1618 1598 1597 1594 1633 1631 1628 1623 1627 1632 1629 1630 1617
 1371 1437 1438 1435 1436 1432 1624 1625 1626 1614 1682
 1411 1406 1407 1408 1409 1420 1419 1415 1410 1417 1416 1412 1418 1421
 1725 1726 1605 1610 1603 1587 1683 1673
                             } 
   claimedprovinces = {   
 1665 1666 1667 1668 1669 1670 1671 1672 1674 1675 1676 1677 1681 1684 1685 1686 #Pacific Island
 1219 #Port Arthur / Dalian
 1245 #Tangshan (border between Manchukuo and Japan under Japanese rule for gameplay reason)
 1683 #Guam 
 #claimed by Japanese for gameplay reason
 1371 #Hong Kong
 1639 1642 1640 1635 1634 1637 1636 1641 1638 1647 1648 1646 1651 1650 1649 1654 1653 1652 1655 1656 1643 1645 1615 1616 1619 1644 1657 1658 1660 1659 1620 1621 1622
 1599 1600 1595 1601 1618 1598 1597 1596 1594 1633 1631 1628 1623 1627 1632 1629 1630 1617 1602 1603 1604 1605 1606 1607 1608 1609 1610 1234 #Indonesia
 1565 1566 1567 1568 1569 1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 #Philippines
 1414 1411 1406 1407 1408 1409 1420 1419 1415 1410 1417 1416 1412 1418 1421 #Burma
 1432 1435 1436 1437 1438 1624 1625 1626 #Malaya & Singapore
 } 	
	# JAP 1944.06 techs 
	# ###################### 
	techapps = { 

	# Manufacturing
	5810 5820 5050 5830 5060 5070 5130
	# Assembly Line
	5140
	# Construction Engineering 
	5800 5080 5090 5100
	# Computers & cryptography
	5310 54010 54020 54030 5320 5360 5330
	5316 5326 5327 5350
	# Agriculture
	5700 5710 5010 5020 5030
	# RADAR
	5410 5416 5417 5420 5426 5430
	# Oil Refining 
	5190 5200
	# Atomics
	5470 5480
	# Medicine
	5600 5610 5620
	# Exp. Rocket
	5560
	# Specialised Equipment
	5940

	# Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110 1120
	# Mountain
	1160 1170 1180 1190 1200 1210 1220 1230 1240 1250
	# Marines
	1560 1570 1580 1590 1600
	# Paratroopers
	1670 1680
	# Cavalry Division  
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 1390
	# Engineers
	1830 1840 1850 1860 1870 
	# Interbellum 1930 Supply 
	1910 1920 1930 1940 1950 1960 1970 1980 1990 199130 199100

	# Tanks 
	7600 7610 2620 2010 2630 2640 2646 2650 2030 2040 2070 2050 
	# Armoured Car  
	2860 2870 2880 2020 2150
	# Field Artillery 
	2290 2300 2310 2900 2910 2920 2930 2940 2320 2330
	# Anti-Tank Artillery 
	2400
	# Static Anti-Air Artillery 
	2800 2450 21180 21190 21200 2460
	# Anti-Air Artillery Brigade 
	2810 2820 2510  

	# Great War Land Doctrines (entente)
	6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
	# Light Infantry Land Doctrines
	6390 6400 6420 6410 6430 6440
	# Armored Division Formation
	6900
	# Hospital System 
	14000 14010 14020 14030

	# Light Cruiser 
	3110 3120 3130 3140 3150 3160 12010
	# Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470
	# Super Heavy Battleship
	3490
	# Battle Cruiser
	3310 3320 3330 3340 3350
	# Heavy Cruiser 
	3210 3220 3230 3240 3250 3260
	# Destroyer 
	3010 3020 3030 3040 3050 3060 3070 12000
	# Submarine
	3610 3620 3630 3640 3650 3660 3670 3710
	# Light carrier 
	12100 12110 12120 12130 12140
	# Fleet Carrier
	3510 3520 3530 3540 3550
	#Torpedo & ASW 18
	3720 3730 3736 3740 3750 3760 3900 3910 3770
	# Troopships
	3810 3820 3830

	# Naval Doctrines
	# Engagement Theories
	8010 8020 8030 8040 8050 8060 8070 8080
	# Naval Supremacy
	8100 8110 8120 8150 8160 8200 8210 8170
	# Naval Interdiction
	8500 8510 8520 8550 8560 8600 8610
	# Engagement Tactics - Fleet-in-Being column
	8900 8910 8920 8930 8940 8950 8960 8970 8980
	# Subsidiary Carrier Role
	81650
	# Aerial Supremacy column
	81700 81710 81720 81730 81740
	# Scouting Focus column
	81850 81860 81870 81880
	# Amphibious Warfare
	82300 82310 82320
	# Naval Logistics
	82500 82510

	# Close Air Support
	4400 4170 4280 4450
	# Interceptors
	4500 4510 4520 4530 4540 4550 4010 4020 4030 4060 4090
	# Escort Fighter
	4050 4080 4110
	# Tactical Bomber 
	4600 4610 4620 4630 4120 4130 4140 4150
	# Naval Bomber 
	4700 4710 4190 4200 4210
	# Transports
	4290 4250
	# Multirole fighter
	4300 4310 4320 4330 4340 4040 4070 4100
	# Seaplanes
	4740 4750 4760 4770 4780 4790 4850 4860
	# Strategic bomber
	4800 4810 4820
	# CAG
	4900 4910 4920 4930 4940

	# Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040 9050 9060 9070 9080 9090 9100 9110 9120 9130 9140 9150 9190
	9200 9210 9220 9350 9230 9240 
	} 

blueprints = { } 
inventions = { 3000027 }

policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 1 
     political_left    = 4 
     freedom           = 1#3 
     free_market       = 3 
     professional_army = 8 
     defense_lobby     = 8 
     interventionism   = 10 
    } 
   headofstate            = {  type = 9 id = 50001  } 
   headofgovernment       = {  type = 9 id = 50022  } 
   foreignminister        = {  type = 9 id = 50050  } # Shigemitsu Mamoru
   armamentminister       = {  type = 9 id = 50074  } # Tojo Hideki 
   ministerofsecurity     = {  type = 9 id = 50330  } # Ando Kisaburo
   ministerofintelligence = {  type = 9 id = 50123  } 
   chiefofstaff           = {  type = 9 id = 50134  } 
   chiefofarmy            = {  type = 9 id = 50143  } 
   chiefofnavy            = {  type = 9 id = 50146  } 
   chiefofair             = {  type = 9 id = 50161  } 
   dormant_ministers      = {  50002 50020 50013 50021 50003 50042 50047 50039 50040 50004 50005 50086 50087 50088 50095 50006 50114 50007 50008 50158
                               50015 50016 50044 50062 50072 50089 50096 50097 50098 50099 50100 50116 50121 50133 50142 50148 50156
                            }
   dormant_teams 		  = { 50017 }	# Yamamoto
  ### Japan Land OOB ### 

   landunit = 
   {  id       = {  type = 13016 id = 1000  } 
     name     = "Shina Hakengun" # China Expeditionary Army
     location = 1338 
     Division = 
     {  id       = {  type = 13016 id = 1001  } 
       name     = "Shina Hakengun shireibu"
       strength  = 80 
       type     = hq 
       model    = 3 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1002  } 
     name     = "Kita Shina Hômengun" # North China Theater Army
     location = 1247 
     Division = 
     {  id       = {  type = 13016 id = 1003  } 
       name     = "Kita Shina Hômengun shireibu"
       strength  = 80 
       type     = hq 
       model    = 3 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1004  } 
       name     = "Dai 27 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1005  } 
     name     = "Kita Shina Hômengun" 
     location = 1341 
     Division = 
     {  id       = {  type = 13016 id = 1014  } 
       name     = "Dai 63 Hoheishidan" 
       strength  = 80
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1007  } 
     name     = "Kita Shina Hômengun" 
     location = 1330 
     Division = 
     {  id       = {  type = 13016 id = 1008  } 
       name     = "Dai 1 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1009  } 
     name     = "Kita Shina Hômengun" 
     location = 1344 
     Division = 
     {  id       = {  type = 13016 id = 1010  } 
       name     = "Dai 7 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1012  } 
       name     = "Dai 8 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 500  } 
     name     = "Moukogo Gun" # Mongol Army
     location = 1269 
     Division = 
     {  id       = {  type = 13016 id = 9  } 
       name     = "Dai 26 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = anti_air 
	   brigade_model = 2
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 10  } 
       name     = "Dai 2 Dokuritsu konsei ryodan" # Independent Mixed Brigade 
       strength = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 11  } 
       name     = "Dai 1 Moukogo Kiheishidan" 
       strength  = 70 
       type     = cavalry 
       model    = 7 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 12  } 
       name     = "Dai 2 Moukogo Kiheishidan" 
       strength  = 70 
       type     = cavalry 
       model    = 7 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 13  } 
       name     = "Dai 3 Moukogo Kiheishidan" 
       strength  = 70 
       type     = cavalry 
       model    = 7 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 14  } 
       name     = "Dai 4 Moukogo Kiheishidan" 
       strength  = 70 
       type     = cavalry 
       model    = 7 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 15  } 
       name     = "Dai 5 Moukogo Kiheishidan" 
       strength  = 70 
       type     = cavalry 
       model    = 7 
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1015  } 
     name     = "Dai 1 Gun" # 1st Army
     location = 1254
     Division = 
     {  id       = {  type = 13016 id = 4  } 
       name     = "Dai 37 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1016  } 
       name     = "Dai 3 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1019  } 
     name     = "Dai 1 Gun" 
     location = 1375
     Division = 
     {  id       = {  type = 13016 id = 1021  } 
       name     = "Dai 9 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1022  } 
       name     = "Dai 69 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1023  } 
     name     = "Dai 12 Gun" # 12th Army
     location = 1320
     Division = 
     {  id       = {  type = 13016 id = 1024  } 
       name     = "Dai 32 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1025  } 
       name     = "Dai 59 Hoheishidan"
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1026  } 
     name     = "Dai 12 Gun" 
     location = 1322
     Division = 
     {  id       = {  type = 13016 id = 1027  } 
       name     = "Dai 5 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1028  } 
       name     = "Dai 6 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1031  } 
     name     = "Dai 11 Gun" 
     location = 1308
     Division = 
     {  id       = {  type = 13016 id = 1032  } 
       name     = "Dai 3 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1033  } 
       name     = "Dai 13 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1037  } 
     name     = "Dai 11 Gun" 
     location = 1308
     Division = 
     {  id       = {  type = 13016 id = 1038  } 
       name     = "Dai 34 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1042  } 
       name     = "Dai 40 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1920  } 
     name     = "Dai 11 Gun" 
     location = 1358
     Division = 
     {  id       = {  type = 13016 id = 1036  } 
       name     = "Dai 68 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1922  } 
     name     = "Dai 11 Gun" 
     location = 1360
     Division = 
     {  id       = {  type = 13016 id = 1039  } 
       name     = "Dai 58 Hoheishidan"
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1043  } 
     name     = "Dai 13 Gun" 
     location = 1340
     Division = 
     {  id       = {  type = 13016 id = 1044  } 
       name     = "Dai 60 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1415  } 
     name     = "Dai 13 Gun" 
     location = 1552
     Division = 
     {  id       = {  type = 13016 id = 5701  } 
       name     = "Dai 29 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = anti_air 
	   brigade_model = 1
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1416  } 
       name     = "Dai 61 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1445  } 
       name     = "Dai 62 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 50 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1045  } 
     name     = "Dai 13 Gun" 
     location = 1308
     Division = 
     {  id       = {  type = 13016 id = 1046  } 
       name     = "Dai 64 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1048  } 
       name     = "Dai 116 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1049  } 
     name     = "Dai 13 Gun" 
     location = 1318
     Division = 
     {  id       = {  type = 13016 id = 1050  } 
       name     = "Dai 65 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1051  } 
       name     = "Dai 17 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1052  } 
     name     = "Dai 13 Gun" 
     location = 1353
     Division = 
     {  id       = {  type = 13016 id = 6  } 
       name     = "Dai 15 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1053  } 
       name     = "Dai 70 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1054  } 
     name     = "Dai 13 Gun" 
     location = 1350
     Division = 
     {  id       = {  type = 13016 id = 1055  } 
       name     = "Dai 22 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1056  } 
     name     = "Dai 23 Gun" 
     location = 1369
     Division = 
     {  id       = {  type = 13016 id = 1058  } 
       name     = "Dai 19 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1059  } 
     name     = "Dai 23 Gun" 
     location = 1370
     Division = 
     {  id       = {  type = 13016 id = 1060  } 
       name     = "Dai 104 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1458  } 
     name     = "Dai 7 Hômengun" # 7th Area Army
     location = 1432 
     Division = 
     {  id       = {  type = 13016 id = 1459  } 
       name     = "Dai 7 Hômengun shireibu"
       strength  = 60 
       type     = hq 
       model    = 3 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1064  } 
     name     = "Dai 25 Gun" 
     location = 1432
     Division = 
     {  id       = {  type = 13016 id = 1447  } 
       name     = "Dai 68 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1432  } 
     name     = "Dai 25 Gun" 
     location = 1636
     Division = 
     {  id       = {  type = 13016 id = 1433  } 
       name     = "Dai 25 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1434  } 
     name     = "Dai 25 Gun" 
     location = 1642
     Division = 
     {  id       = {  type = 13016 id = 1435  } 
       name     = "Dai 26 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1452  } 
     name     = "Dai 29 Gun" 
     location = 1421
     Division = 
     {  id       = {  type = 13016 id = 1453  } 
       name     = "Dai 35 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 40 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1454  } 
       name     = "Dai 36 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 40 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1455  } 
     name     = "Dai 29 Gun" 
     location = 1415
     Division = 
     {  id       = {  type = 13016 id = 1456  } 
       name     = "Dai 37 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1067  } 
     name     = "Konoe Shidan" 
     location = 1552
     Division = 
     {  id       = {  type = 13016 id = 45  } 
       name     = "Dai 1 Konoe Shidan" # Imperial Guards 
       strength  = 90 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1420  } 
       name     = "Dai 2 Konoe Shidan" # Imperial Guards 
       strength  = 90 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1460  } 
       name     = "Dai 3 Konoe Shidan" # Imperial Guards 
       strength  = 90 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 2600  } 
     name     = "Boruneo-jima Chuton Gun" 
     location = 1632
     Division = 
     {  id       = {  type = 13016 id = 2601  } 
       name     = "Teishin Shudan" 
       strength = 50 
       type     = paratrooper 
       model    = 0 
       extra    = glider_artillery 
	   brigade_model = 0
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1400  } 
       name     = "Dai 56 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 40 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 2602  } 
     name     = "Nanpô Gun" 
     location = 1399
     Division = 
     {  id       = {  type = 13016 id = 2603  } 
       name     = "Dai 21 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 70 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1  } 
     name     = "Manchukuo Hakengun" 
     location = 1199 
     Division = 
     {  id       = {  type = 13016 id = 2  } 
       name     = "Manchukuo Hakengun shireibu" 
       strength  = 70 
       type     = hq 
       model    = 3 
       experience = 50
      }   
    } 
   landunit = 
   {  id       = {  type = 13016 id = 16  } 
     name     = "Kantôgun" # Kwantung Theater Army, General Army lvl Changchung, Manchuria  
     location = 1208 
     Division = 
     {  id       = {  type = 13016 id = 17  } 
       name     = "Kantôgun saikô shireibu" # Kwantung Theater Army HQ 
       strength  = 70 
       type     = hq 
       model    = 3 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 18  } 
       name     = "Dai 10 'Himeji' Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       extra    = anti_air 
	   brigade_model = 1
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1478  } 
       name     = "Dai 24 Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 19  } 
       name     = "Dai 28 Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       extra    = anti_air 
	   brigade_model = 1
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 20  } 
       name     = "Kantô Bôbitai" # Kwantung Defence Command 
       strength  = 60 
       type     = garrison 
       model    = 5
       extra    = police 
	   brigade_model = 1
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 21  } 
     name     = "Dai 3 Gun" # Botanko, Manchuko 
     location = 1201 
     Division = 
     {  id       = {  type = 13016 id = 22  } 
       name     = "Dai 9 'Kanazawa' Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 23  } 
       name     = "Dai 12 'Kurume' Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1071  } 
       name     = "Dai 57 Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 24  } 
     name     = "Dai 4 Gun" # Songo, Manchuko 
     location = 1200 
     Division = 
     {  id       = {  type = 13016 id = 25  } 
       name     = "Dai 1 'Tokyo' Hoheishidan" 
       strength  = 75 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 28  } 
     name     = "Dai 5 Gun" # Toan, Manchuko 
     location = 1202 
     Division = 
     {  id       = {  type = 13016 id = 31  } 
       name     = "Dai 3 Manchuko Kiheishidan" 
       strength = 70 
       type     = cavalry 
       model    = 8 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1073  } 
       name     = "Dai 11 Hoheishidan" 
       strength  = 50 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 32  } 
     name     = "Dai 6 Gun" # Hailar, Manchuko 
     location = 1205 
     Division = 
     {  id       = {  type = 13016 id = 33  } 
       name     = "Dai 14 'Utsunomi' Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 7
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 34  } 
       name     = "Dai 23 Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       extra    = police 
	   brigade_model = 1
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 35  } 
     name     = "Dai 20 Gun" # Keinei, Manchuko 
     location = 1204 
     Division = 
     {  id       = {  type = 13016 id = 36  } 
       name     = "Dai 8 'Hirosaki' Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 37  } 
       name     = "Dai 25 Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      } 
    }  
   # Imperial General Headquarters 
   landunit = 
   {  id       = {  type = 13016 id = 46  } 
     name     = "Daihon'ei" # Imperial General HQ Tokyo 
     location = 1552 
     Division = 
     {  id       = {  type = 13016 id = 47  } 
       name     = "Boei Soshireibu" # General Defense HQ 
       strength  = 80 
       type     = hq 
       model    = 2 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1464  } 
       name     = "Dai 81 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1444  } 
       name     = "Dai 60 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1404  } 
       name     = "Dai 63 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1449  } 
       name     = "Dai 73 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 49  } 
     name     = "Kita Hômengun" # North Japan Army 
     location = 1547 
     Division = 
     {  id       = {  type = 13016 id = 50  } 
       name     = "Dai 7 Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 51  } 
       name     = "Dai 57 Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1442  } 
       name     = "Dai 7 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1417  } 
       name     = "Dai 8 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1418  } 
       name     = "Dai 47 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1462  } 
       name     = "Dai 72 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 52  } 
     name     = "Chûô Hômengun" # Central Japan Army 
     location = 1557 
     Division = 
     {  id       = {  type = 13016 id = 1461  } 
       name     = "Dai 44 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 53  } 
       name     = "Dai 53 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = anti_air 
	   brigade_model = 1
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1467  } 
       name     = "Dai 93 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1479  } 
       name     = "Dai 4 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1413  } 
       name     = "Dai 5 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1412  } 
       name     = "Dai 52 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1480  } 
       name     = "Dai 55 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 54  } 
     name     = "Roppou Hômengun" #West Japan Army 
     location = 1559 
     Division = 
     {  id       = {  type = 13016 id = 1481  } 
       name     = "Dai 6 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 55  } 
       name     = "Dai 8 Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       extra    = anti_air 
	   brigade_model = 1
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 56  } 
       name     = "Dai 14 Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       extra    = anti_air 
	   brigade_model = 1
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1443  } 
       name     = "Dai 54 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1482  } 
       name     = "Dai 56 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 57  } 
     name     = "Tôbu Hômengun" # East Japan Army 
     location = 1560 
     Division = 
     {  id       = {  type = 13016 id = 58  } 
       name     = "Dai 52 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = anti_air 
	   brigade_model = 1
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1463  } 
       name     = "Dai 77 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1465  } 
       name     = "Dai 86 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1470  } 
       name     = "Dai 44 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1483  } 
       name     = "Dai 2 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1411  } 
       name     = "Dai 3 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1484  } 
       name     = "Dai 51 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1485  } 
       name     = "Dai 57 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 59  } 
     name     = "Chôsengun" # Korean Army 
     location = 1225 
     Division = 
     {  id       = {  type = 13016 id = 60  } 
       name     = "Dai 19 'Ranan' Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = anti_air 
	   brigade_model = 1
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 71  } 
     name     = "Nanpô Chôsengun" # South Korean Army 
     location = 1228 
     Division = 
     {  id       = {  type = 13016 id = 72  } 
       name     = "Dai 20 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1468  } 
       name     = "Dai 30 Rusu Shidan" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1074  } 
     name     = "Taiwangun" # Taiwan Army 
     location = 1362 
     Division = 
     {  id       = {  type = 13016 id = 1469  } 
       name     = "Dai 50 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1471  } 
       name     = "Dai 45 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 40 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1457  } 
       name     = "Dai 46 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 40 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1077  } 
     name     = "Tokubetsuna tasukufôsu"
     location = 1367 
     Division = 
     {  id       = {  type = 13016 id = 1078  } 
       name     = "Dai 110 Hoheishidan" 
       strength  = 85 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1409  } 
     name     = "Tokubetsuna tasukufôsu" 
     location = 1365
     Division = 
     {  id       = {  type = 13016 id = 1410  } 
       name     = "Dai 22 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1414  } 
       name     = "Dai 23 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1092  } 
     name     = "Nanpô Gun" # Southern Expeditionary Army Group
     location = 1399 
     Division = 
     {  id       = {  type = 13016 id = 1093  } 
       name     = "Nanpô Gun shireibu"
       strength  = 70 
       type     = hq 
       model    = 3 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1125  } 
     name     = "Biruma Hômengun" # Burma Area Army
     location = 1410 
     Division = 
     {  id       = {  type = 13016 id = 1126  } 
       name     = "Biruma Hômengun shireibu"
       strength  = 70 
       type     = hq 
       model    = 3 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1079  } 
     name     = "Dai 33 Gun"
     location = 1407 
     Division = 
     {  id       = {  type = 13016 id = 1070  } 
       name     = "Dai 18 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1450  } 
       name     = "Dai 49 'Okami' Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 44  } 
       name     = "Dai 56 Hoheishidan" 
       strength = 80 
       type     = infantry 
       model    = 11 
       extra    = anti_air 
	   brigade_model = 2
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1921  } 
     name     = "Dai 28 Gun" 
     location = 1420
     Division = 
     {  id       = {  type = 13016 id = 43  } 
       name     = "Dai 2 'Sendai' Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = engineer 
	   brigade_model = 3
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 5300  } 
       name     = "Dai 54 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1066  } 
       name     = "Dai 55 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1081  } 
     name     = "Dai 15 Gun" 
     location = 1406
     Division = 
     {  id       = {  type = 13016 id = 3011  } 
       name     = "Dai 31 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1082  } 
       name     = "Dai 33 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1083  } 
     name     = "Biruma Hômengun" 
     location = 1408
     Division = 
     {  id       = {  type = 13016 id = 1084  } 
       name     = "Dai 5 Teishinshudan" 
       strength  = 60 
       type     = paratrooper 
       model    = 1 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1451  } 
       name     = "Dai 24 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1085  } 
     name     = "Dai 16 Gun" 
     location = 1647
     Division = 
     {  id       = {  type = 13016 id = 1086  } 
       name     = "Dai 46 Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1087  } 
     name     = "Dai 16 Gun" 
     location = 1616
     Division = 
     {  id       = {  type = 13016 id = 41  } 
       name     = "Dai 48 'Formosa' Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1436  } 
     name     = "Dai 16 Gun" 
     location = 1649
     Division = 
     {  id       = {  type = 13016 id = 1437  } 
       name     = "Dai 27 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 50 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1438  } 
     name     = "Dai 16 Gun" 
     location = 1653
     Division = 
     {  id       = {  type = 13016 id = 1439  } 
       name     = "Dai 28 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 50 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1473  } 
     name     = "Dai 14 Hômengun" # 14th Area Army
     location = 1565 
     Division = 
     {  id       = {  type = 13016 id = 1474  } 
       name     = "Dai 14 Hômengun shireibu"
       strength  = 60 
       type     = hq 
       model    = 3 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1088  } 
     name     = "Dai 14 Hômengun" 
     location = 1565
     Division = 
     {  id       = {  type = 13016 id = 48  } 
       name     = "Dai 4 'Osaka' Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1089  } 
     name     = "Dai 14 Hômengun" 
     location = 1571
     Division = 
     {  id       = {  type = 13016 id = 1090  } 
       name     = "Dai 30 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1091  } 
     name     = "Dai 14 Hômengun" 
     location = 1568
     Division = 
     {  id       = {  type = 13016 id = 40  } 
       name     = "Dai 16 'Kyoto' Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = engineer 
	   brigade_model = 3
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1419  } 
     name     = "Dai 32 Gun" 
     location = 1564
     Division = 
     {  id       = {  type = 13016 id = 1020  } 
       name     = "Dai 62 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1446  } 
       name     = "Dai 67 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1423  } 
     name     = "Dai 14 Hômengun" 
     location = 1579
     Division = 
     {  id       = {  type = 13016 id = 1424  } 
       name     = "Dai 30 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 40 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1475  } 
       name     = "Dai 54 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 40 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1476  } 
     name     = "Dai 14 Hômengun" 
     location = 1577
     Division = 
     {  id       = {  type = 13016 id = 1477  } 
       name     = "Dai 55 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 30 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1425  } 
     name     = "Dai 14 Hômengun" 
     location = 1573
     Division = 
     {  id       = {  type = 13016 id = 1426  } 
       name     = "Dai 102 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1427  } 
     name     = "Dai 14 Hômengun" 
     location = 1566
     Division = 
     {  id       = {  type = 13016 id = 1428  } 
       name     = "Dai 32 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1429  } 
       name     = "Dai 33 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1094  } 
     name     = "Dai 8 Hômengun" # 8th Area Army
     location = 1726 
     Division = 
     {  id       = {  type = 13016 id = 1095  } 
       name     = "Dai 8 Hômengun shireibu"
       strength  = 20 
       type     = hq 
       model    = 3 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1061  } 
     name     = "Dai 17 Gun" 
     location = 1726
     Division = 
     {  id       = {  type = 13016 id = 7  } 
       name     = "Dai 17 Hoheishidan" 
       strength  = 30 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1062  } 
       name     = "Dai 38 Hoheishidan" 
       strength  = 30 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1034  } 
     name     = "Dai 17 Gun" 
     location = 1587
     Division = 
     {  id       = {  type = 13016 id = 1035  } 
       name     = "Dai 6 'Kumamoto' Hoheishidan" 
       strength  = 55 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1472  } 
       name     = "Dai 38 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 25 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1097  } 
     name     = "Dai 18 Gun"
     location = 1605 
     Division = 
     {  id       = {  type = 13016 id = 3  } 
       name     = "Dai 36 Hoheishidan" 
       strength  = 30 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1057  } 
       name     = "Dai 51 Hoheishidan" 
       strength  = 30 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1486  } 
     name     = "Dai 18 Gun"
     location = 1600 
     Division = 
     {  id       = {  type = 13016 id = 1006  } 
       name     = "Dai 35 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1421  } 
     name     = "Tai Chuton Gun" 
     location = 1423
     Division = 
     {  id       = {  type = 13016 id = 1422  } 
       name     = "Dai 29 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1107  } 
     name     = "Dai 1 Hômengun" # 1st Area Army
     location = 1214 
     Division = 
     {  id       = {  type = 13016 id = 1108  } 
       name     = "Dai 1 Hômengun shireibu"
       strength  = 60 
       type     = hq 
       model    = 3 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1109  } 
     name     = "Dai 2 Hômengun" # 2nd Area Army
     location = 1659 
     Division = 
     {  id       = {  type = 13016 id = 1110  } 
       name     = "Dai 2 Hômengun shireibu"
       strength  = 60 
       type     = hq 
       model    = 3 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1098  } 
     name     = "Dai 2 Hômengun"
     location = 1622 
     Division = 
     {  id       = {  type = 13016 id = 1069  } 
       name     = "Dai 5 'Hiroshima' Hoheishidan" 
       strength  = 30 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1430  } 
     name     = "Dai 3 Hômengun" # 3rd Area Army
     location = 1203 
     Division = 
     {  id       = {  type = 13016 id = 1431  } 
       name     = "Dai 3 Hômengun shireibu"
       strength  = 60 
       type     = hq 
       model    = 3 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1111  } 
     name     = "Indoshina Chuton Gun"
     location = 1395 
     Division = 
     {  id       = {  type = 13016 id = 1112  } 
       name     = "Dai 21 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1440  } 
     name     = "Indoshina Chuton Gun" 
     location = 1392
     Division = 
     {  id       = {  type = 13016 id = 1441  } 
       name     = "Dai 34 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1115  } 
     name     = "Dai 1 Hômengun"
     location = 1212 
     Division = 
     {  id       = {  type = 13016 id = 1117  } 
       name     = "Dai 2 Senshashidan" 
       strength  = 55 
       type     = armor 
       model    = 0 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1403  } 
       name     = "Dai 71 Hoheishidan" 
       strength  = 70 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1118  } 
     name     = "Kita Shina Hômengun"
     location = 1308 
     Division = 
     {  id       = {  type = 13016 id = 1116  } 
       name     = "Dai 1 Senshashidan" 
       strength  = 55 
       type     = armor 
       model    = 0 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1119  } 
       name     = "Dai 3 Senshashidan" 
       strength  = 50 
       type     = light_armor 
       model    = 2 
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1120  } 
     name     = "Shina Hakengun"
     location = 1345 
     Division = 
     {  id       = {  type = 13016 id = 1121  } 
       name     = "Dai 69 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1122  } 
     name     = "Shina Hakengun"
     location = 1348 
     Division = 
     {  id       = {  type = 13016 id = 1123  } 
       name     = "Dai 115 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
    }
   landunit = 
   {  id       = {  type = 13016 id = 1124  } 
     name     = "Dai 2 Gundan"
     location = 1342 
     Division = 
     {  id       = {  type = 13016 id = 1041  } 
       name     = "Dai 39 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
    }
   landunit = 
   {  id       = {  type = 13016 id = 1099  } 
     name     = "Wake Konkyochi tai"
     location = 1673 
     Division = 
     {  id       = {  type = 13016 id = 1100  } 
       name     = "Maizaru Rikusentai" 
       strength  = 60 
       type     = marine 
       model    = 4 
       experience = 50
      } 
    }
   # Pacific garrisons: 
   landunit = 
   {  id       = {  type = 13016 id = 74  } 
     name     = "Dai 27 Gun" 
     location = 1545
     Division = 
     {  id       = {  type = 13016 id = 1113  } 
       name     = "Dai 7 'Asahigawa' Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 1466  } 
       name     = "Dai 91 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       experience = 50
      }
     Division = 
     {  id       = {  type = 13016 id = 1448  } 
       name     = "Dai 69 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 78  } 
     name     = "Toyohara Chuton Gun" 
     location = 1542 
     Division = 
     {  id       = {  type = 13016 id = 79  } 
       name     = "Toyohara Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 80  } 
     name     = "Tomari Konkyochi tai" 
     location = 1666 
     Division = 
     {  id       = {  type = 13016 id = 81  } 
       name     = "Tomari Keibitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 82  } 
     name     = "Dai 27 Gun" 
     location = 1543 
     Division = 
     {  id       = {  type = 13016 id = 83  } 
       name     = "Dai 42 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 84  } 
     name     = "Mariane Konkyochi tai" 
     location = 1686 
     Division = 
     {  id       = {  type = 13016 id = 85  } 
       name     = "Mariane Keibitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 86  } 
     name     = "Dai 31 Gun" 
     location = 1670 
     Division = 
     {  id       = {  type = 13016 id = 87  } 
       name     = "Dai 53 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 90  } 
     name     = "Bikini Konkyochi tai" 
     location = 1674 
     Division = 
     {  id       = {  type = 13016 id = 91  } 
       name     = "Bikini Keibitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 96  } 
     name     = "Wotje Konkyochi tai" 
     location = 1681 
     Division = 
     {  id       = {  type = 13016 id = 97  } 
       name     = "Wotje Keibitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 98  } 
     name     = "Iwo Jima Konkyochi tai" 
     location = 1661 
     Division = 
     {  id       = {  type = 13016 id = 99  } 
       name     = "Dai 109 Hoheishidan" 
       strength  = 80 
       type     = infantry 
       model    = 11 
       extra    = artillery 
	   brigade_model = 8
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 100  } 
     name     = "Minami Torima Konkyochi tai" 
     location = 1672 
     Division = 
     {  id       = {  type = 13016 id = 101  } 
       name     = "Minami Torima Keibitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 102  } 
     name     = "Dai 31 Gun" 
     location = 1668
     Division = 
     {  id       = {  type = 13016 id = 103  } 
       name     = "Dai 50 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 104  } 
     name     = "Dai 31 Gun" 
     location = 1667
     Division = 
     {  id       = {  type = 13016 id = 105  } 
       name     = "Dai 51 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 50 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 106  } 
     name     = "Dai 31 Gun" 
     location = 1665
     Division = 
     {  id       = {  type = 13016 id = 107  } 
       name     = "Dai 52 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 50 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 110  } 
     name     = "Yap Konkyochi tai" 
     location = 1669
     Division = 
     {  id       = {  type = 13016 id = 111  } 
       name     = "Dai 49 Dokuritsu konsei ryodan" # Independent Mixed Brigade
       strength  = 60 
       type     = infantry 
       model    = 10 
       experience = 50
      }
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1101  } 
     name     = "Omiya Jima Konkyochi tai" 
     location = 1683
     Division = 
     {  id       = {  type = 13016 id = 1102  } 
       name     = "Omiya Jima Keibitai" 
       strength  = 60 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1105  } 
     name     = "Otori-Shima Konkyochi tai" 
     location = 1673
     Division = 
     {  id       = {  type = 13016 id = 1106  } 
       name     = "Dai 65 Gadoyunitto" 
       strength  = 25 
       type     = infantry 
       model    = 10
       experience = 50
      } 
    } 
   landunit = 
   {  id       = {  type = 13016 id = 1131  } 
     name     = "Nauru Konkyochi tai" 
     location = 1682
     Division = 
     {  id       = {  type = 13016 id = 1132  } 
       name     = "Nauru Keibitai" 
       strength  = 20 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 	
   landunit = 
   {  id       = {  type = 13016 id = 1401  } 
     name     = "Shingaporu Chuton Gun" 
     location = 1432 
     Division = 
     {  id       = {  type = 13016 id = 1402  } 
       name     = "Shingaporu Keibitai" 
       strength  = 70 
       type     = garrison 
       model    = 5
       experience = 50
      } 
    } 

  ### Japan Navy OOB ### 
  

	# COMBINED FLEET
	# 4th Battleship Squadron
	navalunit = { 
		id = { type = 13016 id = 1308 } 
		name = "Dai 4 Senkan Sentai" 
		location = 1579 
		base = 1579 
		division = { 
			id = { type = 13016 id = 118 } 
			name = "Fuso" 
			type = battleship 
			model = 3 
			extra1 = naval_improved_hull_l
			extra2 = floatplane
			brigade_model2 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 121 } 
			name = "Ise" 
			type = battleship 
			model = 4 
			extra1 = naval_improved_hull_l
			extra2 = naval_anti_air_l
			extra3 = floatplane
			brigade_model3 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 122 } 
			name = "Hyuga" 
			type = battleship 
			model = 4 
			extra1 = naval_improved_hull_l
			extra2 = naval_anti_air_l
			extra3 = floatplane
			brigade_model3 = 6
			experience = 50
		}
		division = { 
			id = { type = 13016 id = 119 } 
			name = "Yamashiro" 
			type = battleship 
			model = 3 
			extra1 = naval_improved_hull_l
			extra2 = floatplane
			brigade_model2 = 6
			experience = 50
		} 
	}
	# 1st Cruiser Squadron
	navalunit = { 
		id = { type = 13016 id = 2161 } 
		name = "Dai 1 Sentai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 145 } 
			name = "Natori" 
			type = light_cruiser 
			model = 3 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 151 } 
			name = "Isuzu" 
			type = light_cruiser 
			model = 3 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 137 } 
			name = "Nagara" 
			type = light_cruiser 
			model = 3 
			experience = 50
		}
		division = { 
			id = { type = 13016 id = 136 } 
			name = "Oi" 
			type = light_cruiser 
			model = 2 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 3013 } 
			name = "Yahagi" 
			type = light_cruiser 
			model = 6 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 3008 } 
			name = "Oyodo" 
			type = light_cruiser 
			model = 6 
			experience = 50
		} 
	}
	# 1st Destroyer Squadron
	navalunit = { 
		id = { type = 13016 id = 2115 } 
		name = "Dai 1 Kuchiku Sentai" 
		location = 1552 
		base = 1552
		division = { 
			id = { type = 13016 id = 181 } 
			name = "Dai 1 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 182 } 
			name = "Dai 2 Kuchikusentai" 
			type = destroyer 
			model = 3 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 183 } 
			name = "Dai 3 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
		}
		division = { 
			id = { type = 13016 id = 185 } 
			name = "Dai 5 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 186 } 
			name = "Dai 6 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
		}
		division = { 
			id = { type = 13016 id = 195 } 
			name = "Dai 8 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
		} 
    		division = { 
			id = { type = 13016 id = 198 } 
			name = "Dai 11 Kuchikusentai" 
			type = destroyer 
			model = 5 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 199 } 
			name = "Dai 12 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 200 } 
			name = "Dai 13 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
		}
	}
	# 1st Submarine Squadron
	navalunit = { 
		id = { type = 13016 id = 2020 } 
		name = "Dai 1 Sensui Kantai" 
		location = 1661 
		base = 1661 
		division = { 
			id = { type = 13016 id = 226 } 
			name = "Dai 1 Sensuisentai" 
			type = submarine 
			model = 2 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 227 } 
			name = "Dai 2 Sensuisentai" 
			type = submarine 
			model = 2 
			experience = 50
		}
		division = { 
			id = { type = 13016 id = 2021 } 
			name = "Dai 3 Sensuisentai" 
			type = submarine 
			model = 3 
			experience = 50
		}
	}
	# 2nd Submarine Squadron
	navalunit = { 
		id = { type = 13016 id = 2137 } 
		name = "Dai 2 Sensui Kantai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 229 } 
			name = "I-5" 
			type = nuclear_submarine
			model = 0
			extra1 = floatplane
			brigade_model1 = 5
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2321 } 
			name = "I-6" 
			type = nuclear_submarine
			model = 0
			extra1 = floatplane
			brigade_model1 = 5
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2322 } 
			name = "I-8" 
			type = nuclear_submarine
			model = 0
			extra1 = floatplane
			brigade_model1 = 5
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2323 } 
			name = "I-10" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 5
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2324 } 
			name = "I-12" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2325 } 
			name = "I-26" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2326 } 
			name = "I-29" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
	}
	# 9th Submarine Squadron
	navalunit = { 
		id = { type = 13016 id = 2327 } 
		name = "Dai 9 Sensui Kantai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 2328 } 
			name = "I-36" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 5
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2329 } 
			name = "I-37" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 5
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2330 } 
			name = "I-38" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 5
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2331 } 
			name = "I-41" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 5
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2332 } 
			name = "I-44" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2333 } 
			name = "I-45" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2334 } 
			name = "I-54" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2335 } 
			name = "I-56" 
			type = nuclear_submarine
			model = 1
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
	}
	# 3rd Submarine Squadron
	navalunit = { 
		id = { type = 13016 id = 1307 } 
		name = "Dai 3 Sensui Kantai" 
		location = 1579 
		base = 1579 
		division = { 
			id = { type = 13016 id = 2320 } 
			name = "Dai 4 Sensuisentai" 
			type = submarine 
			model = 3 
			experience = 50
		}  
		division = { 
			id = { type = 13016 id = 230 } 
			name = "Dai 6 Sensuisentai" 
			type = submarine 
			model = 4 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 1305 } 
			name = "Dai 7 Sensuisentai" 
			type = submarine 
			model = 5 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 234 } 
			name = "Dai 9 Sensuisentai" 
			type = submarine 
			model = 4 
			experience = 50
		} 
	}
	# 5th Submarine Squadron
	navalunit = { 
		id = { type = 13016 id = 2124 } 
		name = "Dai 5 Sensui Kantai" 
		location = 1670 
		base = 1670 
		division = { 
			id = { type = 13016 id = 2350 } 
			name = "Dai 13 Sensuisentai" 
			type = submarine 
			model = 3 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 1301 } 
			name = "Dai 14 Sensuisentai" 
			type = submarine 
			model = 4 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 1303 } 
			name = "Dai 16 Sensuisentai" 
			type = submarine 
			model = 5 
			experience = 50
		} 
	}
	# 6th Submarine Squadron
	navalunit = { 
		id = { type = 13016 id = 2129 } 
		name = "Dai 6 Sensui Kantai" 
		location = 1667 
		base = 1667 
		division = { 
			id = { type = 13016 id = 1304 } 
			name = "Dai 17 Sensuisentai" 
			type = submarine 
			model = 5 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2121 } 
			name = "Dai 18 Sensuisentai" 
			type = submarine 
			model = 2 
			experience = 50
		} 
	}
	# Akitsushima
	navalunit = { 
		id = { type = 13016 id = 3101 } 
		name = "Akitsushima" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 3100 } 
			name = "Akitsushima" 
			type = escort_carrier 
			model = 0 
		} 
	}
	# Transport Fleet 1
	navalunit = { 
		id = { type = 13016 id = 2142 } 
		name = "Dai 1 Yuso Kantai" 
		location = 1432 
		base = 1432 
		division = { 
			id = { type = 13016 id = 187 } 
			name = "Dai 1 Yuso Sentai" 
			type = transport 
			model = 3 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 188 } 
			name = "Dai 2 Yuso Sentai" 
			type = transport 
			model = 3 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 189 } 
			name = "Dai 3 Yuso Sentai" 
			type = transport 
			model = 3 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 190 } 
			name = "Dai 4 Yuso Sentai" 
			type = transport 
			model = 3 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 191 } 
			name = "Dai 5 Yuso Sentai" 
			type = transport 
			model = 3 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 192 } 
			name = "Dai 6 Yuso Sentai" 
			type = transport 
			model = 3 
			experience = 50
			} 
	}
	# Transport Fleet 2
	navalunit = { 
		id = { type = 13016 id = 2146 } 
		name = "Dai 2 Yuso Kantai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 202 } 
			name = "Dai 7 Yuso Sentai" 
			type = transport 
			model = 2 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 203 } 
			name = "Dai 8 Yuso Sentai" 
			type = transport 
			model = 2 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 208 } 
			name = "Dai 9 Yuso Sentai" 
			type = transport 
			model = 2 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 209 } 
			name = "Dai 10 Yuso Sentai" 
			type = transport 
			model = 2 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 210 } 
			name = "Dai 11 Yuso Sentai" 
			type = transport 
			model = 2 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 211 } 
			name = "Dai 12 Yuso Sentai" 
			type = transport 
			model = 2 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 217 } 
			name = "Dai 13 Yuso Sentai" 
			type = transport 
			model = 2 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 218 } 
			name = "Dai 14 Yuso Sentai" 
			type = transport 
			model = 2 
			experience = 50
			} 
		division = { 
			id = { type = 13016 id = 219 } 
			name = "Dai 15 Yuso Sentai" 
			type = transport 
			model = 2 
			experience = 50
			} 
	}  
	# 11th Aircraft Fleet
	navalunit = { 
		id = { type = 13016 id = 2141 } 
		name = "Dai 11 Kokuki Kantai" 
		location = 1632 
		base = 1632 
		division = {
			id = { type = 13016 id = 261 }
			name = "Notoro"
			type = escort_carrier
			model = 0
			experience = 50
		}  
	}
	# Hosho
	navalunit = { 
		id = { type = 13016 id = 2104 } 
		name = "Hosho" 
		location = 1559 
		base = 1559 
		division = { 
			id = { type = 13016 id = 173 } 
			name = "Hosho" 
			type = escort_carrier 
			model = 2 
			experience = 50
		}  
	}
	# 4th Submarine Squadron
	navalunit = { 
		id = { type = 13016 id = 2120 } 
		name = "Dai 4 Sensui Kantai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 235 } 
			name = "Dai 10 Sensuisentai" 
			type = submarine 
			model = 5 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2351 } 
			name = "Dai 11 Sensuisentai" 
			type = submarine 
			model = 5 
			experience = 50
		} 
	}
	# 2ND FLEET
	# 3rd Carrier Division
	navalunit = { 
		id = { type = 13016 id = 1300 } 
		name = "Dai 3 Koku Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 1790 } 
			name = "Zuiho" 
			type  = light_carrier 
			model = 0 
			experience = 50
			extra = light_cag
			brigade_model = 4
		}  
		division = { 
			id = { type = 13016 id = 3023 } 
			name = "Chiyoda" 
			type  = light_carrier 
			model = 1 
			experience = 50
			extra = light_cag
			brigade_model = 4
		} 
		division = { 
			id = { type = 13016 id = 3022 } 
			name = "Chitose" 
			type  = light_carrier 
			model = 1 
			experience = 50
			extra = light_cag
			brigade_model = 4
		} 
	}
	# 2nd Battleship Squadron
	navalunit = { 
		id = { type = 13016 id = 2002 } 
		name = "Dai 2 Senkan Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 3004 } 
			name = "Yamato" 
			type = battleship 
			model = 11 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 3005 } 
			name = "Musashi" 
			type = battleship 
			model = 11 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
	}
	# 3rd Battleship Squadron
	navalunit = { 
		id = { type = 13016 id = 2003 } 
		name = "Dai 3 Senkan Sentai" 
		location = 1565 
		base = 1565 
 		division = { 
			id = { type = 13016 id = 113 } 
			name = "Kongo" 
			type = battlecruiser 
			model = 3 
			extra1 = naval_improved_hull_l
			extra2 = floatplane
			brigade_model2 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 115 } 
			name = "Haruna" 
			type = battlecruiser 
			model = 3 
			extra1 = naval_improved_hull_l
			extra2 = floatplane
			brigade_model2 = 6
			experience = 50
		} 
	}
	# 4th Cruiser Squadron
	navalunit = { 
		id = { type = 13016 id = 2013 } 
		name = "Dai 4 Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 165 } 
			name = "Atago" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 166 } 
			name = "Takao" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 167 } 
			name = "Chokai" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		}
		division = { 
			id = { type = 13016 id = 169 } 
			name = "Maya" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		}
	}
	# 7th Cruiser Squadron
	navalunit = { 
		id = { type = 13016 id = 2011 } 
		name = "Dai 7 Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 264 } 
			name = "Kumano" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		}
		division = { 
			id = { type = 13016 id = 265 } 
			name = "Suzuya" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		}
		division = { 
			id = { type = 13016 id = 266 } 
			name = "Tone" 
			type = heavy_cruiser 
			model = 5 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		}
		division = { 
			id = { type = 13016 id = 267 } 
			name = "Chikuma" 
			type = heavy_cruiser 
			model = 5 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		}
	}
	# 2nd Destroyer Squadron
	navalunit = { 
		id = { type = 13016 id = 2015 } 
		name = "Dai 2 Kuchiku Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 3012 } 
			name = "Noshiro" 
			type = light_cruiser 
			model = 6 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2251 } 
			name = "Dai 27 Kuchikusentai" 
			type = destroyer 
			model = 3
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2255 } 
			name = "Dai 31 Kuchikusentai" 
			type = destroyer 
			model = 4
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2256 } 
			name = "Dai 32 Kuchikusentai" 
			type = destroyer 
			model = 4
			experience = 50
		} 
	}
	# 3RD FLEET
	# 1st Carrier Division
	navalunit = { 
		id = { type = 13016 id = 112 } 
		name = "Dai 1 Koku Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 3003 } 
			name = "Zuikaku" 
			type = carrier 
			model = 3 
			extra1 = cag 
			brigade_model1 = 5 
			experience = 50
		} 
	}
	# 2nd Carrier Division
	navalunit = { 
		id = { type = 13016 id = 2139 } 
		name = "Dai 2 Koku Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 3010 } 
			name = "Junyo" 
			type = carrier 
			model = 0 
			extra1 = cag 
			brigade_model1 = 5 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 3016 } 
			name = "Ryuho" 
			type  = light_carrier 
			model = 0 
			experience = 50
			extra = light_cag
			brigade_model = 4
		} 
	}
	# 1st Battleship Squadron
	navalunit = { 
		id = { type = 13016 id = 2000 } 
		name = "Dai 1 Senkan Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 123 } 	
			name = "Nagato" 
			type = battleship 
			model = 5 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = floatplane
			brigade_model3 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 3021 } 
			name = "Mogami" 
			type = heavy_cruiser 
			model = 4 
			extra1 = naval_anti_air_s
			extra2 = floatplane
			brigade_model2 = 6
			experience = 50
		} 
	}
	# 5th Cruiser Squadron
	navalunit = { 
		id = { type = 13016 id = 2018 } 
		name = "Dai 2 Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 163 } 
			name = "Myoko" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		}
		division = { 
			id = { type = 13016 id = 160 } 
			name = "Haguro" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		}
	}
	# 10th Destroyer Squadron
	navalunit = { 
		id = { type = 13016 id = 1315 } 
		name = "Dai 10 Kuchiku Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 184 } 
			name = "Dai 4 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
			} 
		division = { 
			id = { type = 13016 id = 197 } 
			name = "Dai 10 Kuchikusentai" 
			type = destroyer 
			model = 5 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 207 } 
			name = "Dai 17 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 1316 } 
			name = "Dai 61 Kuchikusentai" 
			type = destroyer 
			model = 7 
			experience = 50
		} 
	}
	# 5TH FLEET
	# 16th Cruiser Squadron
	navalunit = { 
		id = { type = 13016 id = 1318 } 
		name = "Dai 16 Sentai" 
		location = 1552 
		base = 1552 
		division = { 
			id = { type = 13016 id = 157 } 
			name = "Aoba" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 146 } 
			name = "Kinu" 
			type = light_cruiser 
			model = 3 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 132 } 
			name = "Kitakami" 
			type = light_cruiser 
			model = 2 
			experience = 50
		}
	}
	# 21st Cruiser Squadron
	navalunit = { 
		id = { type = 13016 id = 2012 } 
		name = "Dai 21 Sentai" 
		location = 1545 
		base = 1545 
		division = { 
			id = { type = 13016 id = 159 } 
			name = "Nachi" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 164 } 
			name = "Ashigara" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 6
			experience = 50
		}
 		division = { 
			id = { type = 13016 id = 131 } 
			name = "Tama" 
			type = light_cruiser 
			model = 2 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 135 } 
			name = "Kiso" 
			type = light_cruiser 
			model = 2 
			experience = 50
		} 
	}
	# 1st Cruiser Destroyer Squadron
	navalunit = { 
		id = { type = 13016 id = 2019 } 
		name = "Dai 1 Kuchiku Sentai" 
		location = 1545  
		base = 1545 
 		division = { 
			id = { type = 13016 id = 153 } 
			name = "Abukuma" 
			type = light_cruiser 
			model = 3 
			experience = 50
                        extra1 = floatplane
                        brigade_model1 = 3
                        extra2 = naval_torpedoes_s
                        brigade_model2 = 0
		} 
		division = { 
			id = { type = 13016 id = 194 } 
			name = "Dai 7 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 213 } 
			name = "Dai 18 Kuchikusentai" 
			type = destroyer 
			model = 4 
			experience = 50
		}   
		division = { 
			id = { type = 13016 id = 268 } 
			name = "Dai 21 Kuchikusentai" 
			type = destroyer
			model = 4
			experience = 50
		}
	}
	# 6TH FLEET
	# 7th Submarine Squadron
	navalunit = { 
		id = { type = 13016 id = 2131 } 
		name = "Dai 7 Sensui Kantai" 
		location = 1683 
		base = 1683 
		division = { 
			id = { type = 13016 id = 1310 } 
			name = "Dai 51 Sensuisentai" 
			type = submarine 
			model = 6 
			experience = 50
		} 
	}
	# 8th Submarine Squadron
	navalunit = { 
		id = { type = 13016 id = 1311 } 
		name = "Dai 8 Sensui Kantai" 
		location = 1683 
		base = 1683 
		division = { 
			id = { type = 13016 id = 1306 } 
			name = "Dai 8 Sensuisentai" 
			type = submarine 
			model = 5 
			experience = 50
		} 
	}
	# 11th Submarine Squadron
	navalunit = { 
		id = { type = 13016 id = 1312 } 
		name = "Dai 11 Sensui Kantai" 
		location = 1683 
		base = 1683 
		division = { 
			id = { type = 13016 id = 2352 } 
			name = "Dai 12 Sensuisentai" 
			type = submarine 
			model = 5 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 1302 } 
			name = "Dai 15 Sensuisentai" 
			type = submarine 
			model = 4 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 1313 } 
			name = "Dai 22 Sensuisentai" 
			type = submarine 
			model = 5 
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 1314 } 
			name = "Dai 34 Sensuisentai" 
			type = submarine 
			model = 6 
			experience = 50
		} 
	}
	# 8TH FLEET
	# 3rd Destroyer Squadron
	navalunit = { 
		id = { type = 13016 id = 1317 } 
		name = "Dai 3 Kuchiku Sentai" 
		location = 1565 
		base = 1565 
		division = { 
			id = { type = 13016 id = 2246 } 
			name = "Dai 22 Kuchikusentai" 
			type = destroyer
			model = 2
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 2254 } 
			name = "Dai 30 Kuchikusentai" 
			type = destroyer 
			model = 4
			experience = 50
		} 
	}
	# RESERVE FLEET
	# Crappy Reserve Fleet 1
	navalunit = { 
		id = { type = 13016 id = 231 } 
		name = "Dai 7 Sentai" 
		location = 1560 
		base = 1560 
		division = { 
			id = { type = 13016 id = 148 } 
			name = "Asama" 
			type = heavy_cruiser 
			model = 1 
			experience = 50
		} 
		division = {
			id = { type = 13016 id = 258 }
			name = "Iwate"
			type = heavy_cruiser
			model = 1
			experience = 50
		} 
	}
	# Crappy Reserve Fleet 2
	navalunit = { 
		id = { type = 13016 id = 212 } 
		name = "Dai 9 Sentai" 
		location = 1554 
		base = 1554 
		division = {
			id = { type = 13016 id = 262 }
			name = "Yakumo"
			type = heavy_cruiser
			model = 1
			experience = 50
		} 
		division = { 
			id = { type = 13016 id = 138 } 
			name = "Izumo" 
			type = heavy_cruiser 
			model = 1
			experience = 50
		}
	} 


  ### Japan Air OOB ### 
   airunit = 
   {  id       = {  type = 13016 id = 900  } 
     name     = "Daihon'ei Kokutai" 
     location = 1552 
     base     = 1552 
     Division = 
     {  id       = {  type = 13016 id = 901  } 
       name     = "70/71 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 902  } 
       name     = "5/56 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 903  } 
       name     = "244/582 Kok" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 904  } 
     name     = "Daihon'ei Kokutai" 
     location = 1553 
     base     = 1553 
     Division = 
     {  id       = {  type = 13016 id = 905  } 
       name     = "244/246 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 906  } 
     name     = "Dai 12 Kokutai" 
     location = 1545 
     base     = 1545 
     Division = 
     {  id       = {  type = 13016 id = 907  } 
       name     = "Z1/Z3 752 Kok" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 908  } 
       name     = "28/78 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 909  } 
     name     = "Kantô Kokutai" 
     location = 1199 
     base     = 1199 
     Division = 
     {  id       = {  type = 13016 id = 910  } 
       name     = "9/48 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 911  } 
       name     = "3/6 Sentai" 
       strength = 100 
       type     = cas 
       model    = 3
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 912  } 
     name     = "Kita Shina Kokutai" 
     location = 1252 
     base     = 1252 
     Division = 
     {  id       = {  type = 13016 id = 913  } 
       name     = "25/85 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 914  } 
       name     = "32/79 Sentai" 
       strength = 100 
       type     = cas 
       model    = 3
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 915  } 
       name     = "39/49 Sentai" 
       strength = 100 
       type     = tactical_bomber 
       model    = 6
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 916  } 
       name     = "7/74 Sentai" 
       strength = 100 
       type     = tactical_bomber 
       model    = 6
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 917  } 
     name     = "Minami Shina Kokutai" 
     location = 1369 
     base     = 1369 
     Division = 
     {  id       = {  type = 13016 id = 918  } 
       name     = "57/254 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 919  } 
       name     = "34/35 Sentai" 
       strength = 100 
       type     = tactical_bomber 
       model    = 6
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 920  } 
       name     = "36/37 Sentai" 
       strength = 100 
       type     = tactical_bomber 
       model    = 6
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 921  } 
       name     = "58/247 Sentai" 
       strength = 100 
       type     = tactical_bomber 
       model    = 6
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 922  } 
     name     = "Dai 15 Gun Kokutai" 
     location = 1415 
     base     = 1415 
     Division = 
     {  id       = {  type = 13016 id = 923  } 
       name     = "1/21 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 924  } 
       name     = "60/75 Sentai" 
       strength = 100 
       type     = tactical_bomber 
       model    = 6
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 925  } 
       name     = "90/98 Sentai" 
       strength = 100 
       type     = tactical_bomber 
       model    = 6
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 926  } 
     name     = "Dai 15 Gun Kokutai" 
     location = 1409 
     base     = 1409 
     Division = 
     {  id       = {  type = 13016 id = 927  } 
       name     = "64/68 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 928  } 
       name     = "11/157 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 929  } 
     name     = "Dai 2 Hômengun Kokutai" 
     location = 1659 
     base     = 1659 
     Division = 
     {  id       = {  type = 13016 id = 930  } 
       name     = "381/153 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 931  } 
       name     = "251/753 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 932  } 
     name     = "Dai 18 Gun Kokutai" 
     location = 1605 
     base     = 1605 
     Division = 
     {  id       = {  type = 13016 id = 933  } 
       name     = "77/78 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 934  } 
       name     = "301/603 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 935  } 
       name     = "732/751 Sentai" 
       strength = 100 
       type     = naval_bomber 
       model    = 4
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 936  } 
     name     = "Dai 2 Kokutai" 
     location = 1579 
     base     = 1579 
     Division = 
     {  id       = {  type = 13016 id = 937  } 
       name     = "52/331/201 Sentai" 
       strength = 100 
       type     = multi_role 
       model    = 6
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 938  } 
       name     = "19/17/65 Sentai" 
       strength = 100 
       type     = multi_role 
       model    = 6
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 939  } 
     name     = "Dai 2 Kokutai" 
     location = 1566 
     base     = 1566 
     Division = 
     {  id       = {  type = 13016 id = 940  } 
       name     = "20/30/45 Sentai" 
       strength = 100 
       type     = multi_role 
       model    = 6
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 941  } 
       name     = "1/18/73 Sentai" 
       strength = 100 
       type     = multi_role 
       model    = 6
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 942  } 
       name     = "22/51 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 943  } 
       name     = "26/33 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 944  } 
       name     = "8/14 Sentai" 
       strength = 100 
       type     = tactical_bomber 
       model    = 6
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 945  } 
       name     = "16/245 Sentai" 
       strength = 100 
       type     = tactical_bomber 
       model    = 6
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 946  } 
     name     = "Taiwangun Kokutai" 
     location = 1362 
     base     = 1362 
     Division = 
     {  id       = {  type = 13016 id = 947  } 
       name     = "13/29/67 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 948  } 
       name     = "10/76 Sentai" 
       strength = 100 
       type     = cas 
       model    = 3
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 949  } 
     name     = "Rengo Kantai A" 
     location = 1683 
     base     = 1683 
     Division = 
     {  id       = {  type = 13016 id = 950  } 
       name     = "T11/T12 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 951  } 
       name     = "523/121 Sentai" 
       strength = 100 
       type     = cas 
       model    = 3
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 952  } 
       name     = "521/761 Sentai" 
       strength = 100 
       type     = naval_bomber 
       model    = 4
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 953  } 
     name     = "Rengo Kantai B" 
     location = 1670 
     base     = 1670 
     Division = 
     {  id       = {  type = 13016 id = 954  } 
       name     = "265/Hyo Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 955  } 
       name     = "121/253 Sentai" 
       strength = 100 
       type     = cas 
       model    = 3
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 956  } 
     name     = "Rengo Kantai B" 
     location = 1670 
     base     = 1670 
     Division = 
     {  id       = {  type = 13016 id = 957  } 
       name     = "K11/K12 Sentai" 
       strength = 100 
       type     = interceptor 
       model    = 10
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 958  } 
       name     = "151/503 Sentai" 
       strength = 100 
       type     = naval_bomber 
       model    = 4
       experience = 50
      } 
     Division = 
     {  id       = {  type = 13016 id = 959  } 
       name     = "313/551 Sentai" 
       strength = 100 
       type     = naval_bomber 
       model    = 4
       experience = 50
      } 
    } 
   airunit = 
   {  id       = {  type = 13016 id = 960  } 
     name     = "Daihon'ei Kokutai" 
     location = 1560 
     base     = 1560 
     Division = 
     {  id       = {  type = 13016 id = 961  } 
       name     = "4/59 Sentai" 
       strength = 100 
       type     = multi_role 
       model    = 7
       experience = 50
      } 
    } 

   # ### Under division_development ###  
	division_development = {  
		name  = "Shinano" 
		type  = carrier 
		model = 5 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3006  } 
		date  = {  year = 1944 month = november day = 19  } 
		extra = cag 
		brigade_model = 5 
	}
	division_development = {  
		name  = "Sakawa" 
		type  = light_cruiser 
		model = 6 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3014  } 
		date  = {  year = 1944 month = november day = 29  } 
	}
	division_development = {  
		name  = "Ibuki" 
		type  = light_carrier 
		model = 1 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3015  } 
		date  = {  year = 1945 month = september day = 1  } 
		extra = light_cag
		brigade_model = 5
	}
	division_development = {  
		name  = "Unryu" 
		type  = carrier 
		model = 3 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3018  } 
		date  = {  year = 1944 month = august day = 6  } 
		extra = cag 
		brigade_model = 5 
	}
	division_development = {  
		name  = "Amagi" 
		type  = carrier 
		model = 3 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3019  } 
		date  = {  year = 1944 month = august day = 10  } 
		extra = cag 
		brigade_model = 5 
	}
	division_development = {  
		name  = "Katsuragi" 
		type  = carrier 
		model = 3 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3020  } 
		date  = {  year = 1944 month = october day = 3  } 
		extra = cag 
		brigade_model = 5 
	}
	division_development = {  
		name  = "Kasagi" 
		type  = carrier 
		model = 3 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3026  } 
		date  = {  year = 1945 month = june day = 1  } 
		extra = cag 
		brigade_model = 5 
	}
	division_development = {  
		name  = "Aso" 
		type  = carrier 
		model = 3 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3027  } 
		date  = {  year = 1945 month = september day = 1  } 
		extra = cag 
		brigade_model = 5 
	}
	division_development = {  
		name  = "Ikoma" 
		type  = carrier 
		model = 3 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3028  } 
		date  = {  year = 1945 month = october day = 1  } 
		extra = cag 
		brigade_model = 5 
	}
	division_development = {  
		name  = "Ioshima" 
		type  = light_cruiser 
		model = 1 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3024  } 
		date  = {  year = 1944 month = june day = 28  }
		extra1 = naval_anti_air_s
		extra2 = naval_radar_s
	}
	division_development = {  
		name  = "Yasoshima" 
		type  = light_cruiser 
		model = 1 
		new_model = no
		cost  = 0.1
		id    = {  type = 13016 id = 3025  } 
		date  = {  year = 1944 month = september day = 25  }
		extra1 = naval_anti_air_s
		extra2 = naval_radar_s
	}
	division_development = {
		name = "I-13"
		type = nuclear_submarine
		model = 1
		cost = 0.1
		extra1 = floatplane
		brigade_model1 = 5
		id = { type = 13016 id = 3030 }
		date = { year = 1944 month = december day = 15 }
	}
	division_development = {
		name = "I-14"
		type = nuclear_submarine
		model = 1
		cost = 0.1
		extra1 = floatplane
		brigade_model1 = 5
		id = { type = 13016 id = 3031 }
		date = { year = 1945 month = march day = 13 }
	}
	division_development = {
		name = "I-58"
		type = nuclear_submarine
		model = 1
		cost = 0.1
		extra1 = floatplane
		brigade_model1 = 5
		id = { type = 13016 id = 3032 }
		date = { year = 1944 month = september day = 6 }
	}
	division_development = {
		name = "I-400"
		type = nuclear_submarine
		model = 2
		cost = 0.1
		extra1 = floatplane
		brigade_model1 = 5
		extra2 = naval_improved_hull_s
		brigade_model2 = 0
		id = { type = 13016 id = 3033 }
		date = { year = 1944 month = december day = 29 }
	}
	division_development = {
		name = "I-401"
		type = nuclear_submarine
		model = 2
		cost = 0.1
		extra1 = floatplane
		brigade_model1 = 5
		extra2 = naval_improved_hull_s
		brigade_model2 = 0
		id = { type = 13016 id = 3034 }
		date = { year = 1945 month = january day = 7 }
	}
	division_development = {
		name = "I-402"
		type = nuclear_submarine
		model = 2
		cost = 0.1
		extra1 = floatplane
		brigade_model1 = 5
		extra2 = naval_improved_hull_s
		brigade_model2 = 0
		id = { type = 13016 id = 3035 }
		date = { year = 1945 month = july day = 23 }
	}
  } 
 
